### ISSUE TITLE
Throttled

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#100]
This issue has been raised in conversation but I think it worth recording here.

Using release 0.26.

Using the sandbox I have code which allows a user ( ie user1 ) to attempt to acquire a tree of data restricted to self-employments and to one tax year.  Given the use of HATEOAS this results in over 100 calls!  This process then fails part way through with a 429 :

{ "code" : "MESSAGE_THROTTLED_OUT", "message" : "The request for the API is throttled as you have exceeded your quota." }

The attempt to acquire a tree of data restricted to self-employments and to one tax year does not seem unreasonable to me, what do you think?  How should I go about acquiring this information?

Regards

Andrew Smith

### #      Result Protocol      Host                 URL    Body   Caching Content-Type   Process Comments       Custom 
2090   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment      69     no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2120   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663   115    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2129   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17  475    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2138   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/employments     628       no-cache,no-store,max-age=0   application/hal+json  te.processhost.managed:14248                
2147   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/uk-properties   642       no-cache,no-store,max-age=0   application/hal+json  te.processhost.managed:14248                
2156   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/furnished-holiday-lettings      733    no-cache,no-store,max-age=0   application/hal+json  te.processhost.managed:14248                
2161   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments 663       no-cache,no-store,max-age=0   application/hal+json  te.processhost.managed:14248                
2167   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e 1,157  no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2185   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/balancing-charges     922    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2232   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/balancing-charges/5755b92f3d18002a53d3ecd7   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2233   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/balancing-charges/5755b92f3d18002a53d3ecd8   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2242   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/balancing-charges/5755b92f3d18002a53d3ecd9   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2251   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/balancing-charges/5755b92f3d18002a53d3ecda   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2258   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/balancing-charges/5755b92f3d18002a53d3ecdb   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2261   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/goods-and-services-own-uses   992    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2269   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/goods-and-services-own-uses/5755b9364616009361b52c23 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2279   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/goods-and-services-own-uses/5755b9364616009361b52c24 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2280   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/goods-and-services-own-uses/5755b9364616009361b52c25 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2289   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/goods-and-services-own-uses/5755b9364616009361b52c26 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2300   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/goods-and-services-own-uses/5755b9364616009361b52c27 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2311   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/expenses       859    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2320   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/expenses/5755b9374616001261b52c28     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2329   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/expenses/5755b9374616001261b52c29     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2338   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/expenses/5755b9374616001261b52c2a     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2339   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/expenses/5755b9374616001261b52c2b     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2348   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/expenses/5755b9374616001261b52c2c     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2361   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/incomes 852    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2366   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/incomes/5755b9383d18002c53d3ecdc     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2375   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/incomes/5755b9383d18002c53d3ecdd     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2376   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/incomes/5755b9383d18002c53d3ecde     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2385   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/incomes/5755b9383d18002c53d3ecdf     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2394   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1e/incomes/5755b9383d18002c53d3ece0     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2399   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f 1,157  no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2404   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/balancing-charges     922    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2413   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/balancing-charges/5755b939c414009855fcc131   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2418   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/balancing-charges/5755b939c414009855fcc132   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2423   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/balancing-charges/5755b939c414009855fcc133   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2432   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/balancing-charges/5755b939c414009855fcc134   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2441   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/balancing-charges/5755b939c414009855fcc135   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2446   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/goods-and-services-own-uses   992    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2451   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/goods-and-services-own-uses/5755b93a221b00ea553617d3 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2460   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/goods-and-services-own-uses/5755b93a221b00ea553617d4 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2465   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/goods-and-services-own-uses/5755b93a221b00ea553617d5 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2470   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/goods-and-services-own-uses/5755b93a221b00ea553617d6 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2479   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/goods-and-services-own-uses/5755b93a221b00ea553617d7 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2484   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/expenses       859    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2493   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/expenses/5755b93bc414008255fcc136     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2498   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/expenses/5755b93bc414008255fcc137     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2507   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/expenses/5755b93bc414008255fcc138     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2514   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/expenses/5755b93bc414008255fcc139     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2517   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/expenses/5755b93bc414008255fcc13a     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2526   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/incomes 852    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2527   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/incomes/5755b93c3d18002c53d3ece1     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2536   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/incomes/5755b93c3d18002c53d3ece2     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2541   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/incomes/5755b93c3d18002c53d3ece3     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2546   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/incomes/5755b93c3d18002c53d3ece4     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2555   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c1f/incomes/5755b93c3d18002c53d3ece5     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2556   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20 1,157  no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2565   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/balancing-charges     922    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2574   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/balancing-charges/5755b93d3d18000953d3ece6   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2575   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/balancing-charges/5755b93d3d18000953d3ece7   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2584   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/balancing-charges/5755b93d3d18000953d3ece8   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2585   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/balancing-charges/5755b93d3d18000953d3ece9   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2594   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/balancing-charges/5755b93d3d18000953d3ecea   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2601   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/goods-and-services-own-uses   992    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2604   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/goods-and-services-own-uses/5755b93e221b00da553617d8 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2613   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/goods-and-services-own-uses/5755b93e221b00da553617d9 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2614   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/goods-and-services-own-uses/5755b93e221b00da553617da 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2623   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/goods-and-services-own-uses/5755b93e221b00da553617db 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2632   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/goods-and-services-own-uses/5755b93e221b00da553617dc 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2633   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/expenses       859    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2642   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/expenses/5755b93f3d18002c53d3eceb     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2651   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/expenses/5755b93f3d18002c53d3ecec     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2652   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/expenses/5755b93f3d18002c53d3eced     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2665   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/expenses/5755b93f3d18002c53d3ecee     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2670   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/expenses/5755b93f3d18002c53d3ecef     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2679   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/incomes 852    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2688   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/incomes/5755b9403d1800cc51d3ecf0     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2697   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/incomes/5755b9403d1800cc51d3ecf1     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2706   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/incomes/5755b9403d1800cc51d3ecf2     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2707   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/incomes/5755b9403d1800cc51d3ecf3     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2716   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c20/incomes/5755b9403d1800cc51d3ecf4     205    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2725   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21 1,157  no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2734   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/balancing-charges     922    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2739   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/balancing-charges/5755b941c41400b355fcc13b   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2744   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/balancing-charges/5755b941c41400b355fcc13c   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2753   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/balancing-charges/5755b941c41400b355fcc13d   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2764   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/balancing-charges/5755b941c41400b355fcc13e   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2773   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/balancing-charges/5755b941c41400b355fcc13f   213    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2784   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/goods-and-services-own-uses   992    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2793   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/goods-and-services-own-uses/5755b942c41400b355fcc140 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2801   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/goods-and-services-own-uses/5755b942c41400b355fcc141 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2803   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/goods-and-services-own-uses/5755b942c41400b355fcc142 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2812   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/goods-and-services-own-uses/5755b942c41400b355fcc143 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2817   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/goods-and-services-own-uses/5755b942c41400b355fcc144 207    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2830   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/expenses       859    no-cache,no-store,max-age=0   application/hal+json       te.processhost.managed:14248                
2831   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/expenses/5755b943221b00b3563617dd     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2840   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/expenses/5755b943221b00b3563617de     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2849   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/expenses/5755b943221b00b3563617df     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2850   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/expenses/5755b943221b00b3563617e0     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2859   200    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/expenses/5755b943221b00b3563617e1     209    no-cache,no-store,max-age=0       application/hal+json  te.processhost.managed:14248                
2868   429    HTTPS  api.service.hmrc.gov.uk      /self-assessment/9000071663/2016-17/self-employments/5755b92e461600165fb52c21/incomes 121    no-cache, max-age=0   application/json; charset=UTF-8       te.processhost.managed:14248

**Comment by alexec** [comment]
Hi Andy, We have enhanced the list requests (e.g. `/expenses`) to embed the listed items. Once this is released, you should not, therefore, need to do as many requests to retrieve those items. Note: if you traverse the links (especially the `self` links in the list requests), then you'll be make requests that you do not need to do. This will be released within the next two weeks.
