### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#106]
I note the API Documentation has been updated.  Does this reflect 0.39?  If so why is 0.39 marked as pre-release?

**Comment by rakeshavasarala** [comment]
Release tag 0.38.0 was deployed to environment accessible by 3rd party Dev's on 29-June-2016 and is is marked as 'Latest'. 
Please check https://github.com/hmrc/self-assessment-api/blob/master/CHANGELOG.md.
Git Tags marked as 'Pre-Release' are only deployed to internal testing environments of HMRC which is not accessible to 3rd party dev's.
