### ISSUE TITLE
Re Throttling - Issue 100

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#115]
Can you confirm that 0.38 works in terms of getting a tree of data because the throttle limit has been relaxed?

Can you give an indication of what the throttle limit currently is?

Do you have an eta for the 'embedded' solution you mentioned in your answer to #100?

**Comment by alexec** [comment]
Hi @rakeshavasarala  - are you able to answer this for Andy please?

**Comment by rakeshavasarala** [comment]
Version 0.38.0 now Returns full object representations along with links in list responses for both sources and summaries

**Comment by andyws** [comment]
This is clearly a good change and achieves the acquisition of data with far fewer interactions.  Whether it is still too chatty is I believe still an open question and depends in part upon how the throttle is set.  

My current concern however is that there is no formal statement of the structure of data.  While I accept that you will always endeavour to maximise backward compatibility it seems to me that in the absence of a formal statement of data structures there is an inherent fragility in the HATEOAS approach you have adopted.

Please would you consider an OData interface to complement the HATEOAS interface.

**Comment by alexec** [comment]
Hi @andyws, 

Good to hear from you. We always appreciate feedback. I'm glad you can do fewer requests. It sounds like you'd like to do even fewer. What if we were to embed the summaries into each source?

Alex

**Comment by andyws** [comment]
Hi Alex,

"I don't know" is my considered answer!

It occurs to me that the shape of the data being returned and whether any given node within that tree is a link and/or content(ie state) depends upon the expected usage as well as minimising the chatter between an app and HMRC.

This leads me to wonder if it is possible to submit metadata with requests which would allow the client to dictate the shape of the data being returned, a bit like a customised query or view.  As sure as eggs is eggs whatever I suggest for my app will not be optimal for a different app.  

This is something which an OData interface would offer.  I am curious as to whether there are approaches which offer something similar in the context of HATEOAS.

It has occurred to me to construct a cache of data in my app and provide an OData interface.  However in the absence of any mechanism for listening to changes wrt a given UTR I do not see this as practical.


Regards

Andy

**Comment by GlassAndOneHalf** [comment]
Going to close this issue. Please open another if you wish to discuss this topic further.

Thanks,
Jacob
