### ISSUE TITLE
Release 0.53

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#182]
Are there any release notes for 0.53?

Does the 3rd party developer backend support testable calculations?

**Comment by rakeshavasarala** [comment]
Version 0.53 has not been released yet. Forgot to update the tag to 'Pre-Release'. We hope to release it sometime next week and then Release Notes will be updated.

**Comment by danmassie** [comment]
@andyws At the moment we don't support testable calculations.

**Comment by andyws** [comment]
With the "Release" next week I do hope that you will be able to supply details of what is embedded and what is linked for the whole Graph, rather than leaving 3rd party devs to have to discover this operationally.  

Am I likely to be disappointed?

**Comment by danmassie** [comment]
We are working on improving our documentation and will continue iterating on it.
