### ISSUE TITLE
HATEOAS, HAL and the HMRC API

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#191]
HATEOAS (aka Hypermedia as the Engine of Application State) has been adopted by HMRC for the Self-Assessment API (SA API).

This appears to be a choice made by a specific product team within HMRC rather than a general policy for all HMRC APIs.  Certainly the available APIs prior to the appearance of the Self-Assessment API did not follow this approach.

As of the time of writing the currently released version of the Self Assessment API available for developers to test against is 0.38.0.

A host of questions have arisen as a result of our efforts to track and test the SA API.

Is HATEOAS a good choice for the SA API?

Each tax year HMRC defines the set of data structures required to capture the relevant tax code for SA.  Amendments may be required but it hardly counts as volatile.

So, suppose you need to get the SA details for a specific UTR.

Using the API as provided first get or ‘resolve’ the user/UTR.  This is the first call and it provides a starting node.  This node is structured using HAL (Hypertext Application Language).  This node, and all subsequent nodes, contains three elements:

•Links – A self-referencing URL and 0 or more URLs to linked nodes in the graph
•Embedded content – A subset of the content that would be obtained from the above links
•State – The current state of this node represented using strings, ints, bools et al

Then traverse the Graph to obtain the nodes required using links in Links or Links in the Embedded content to obtain the subset of information required.  Given how vast and detailed SA is you will see immediately that the Graph which represents a UTR for a given tax year is huge.  As a result it should be obvious that to obtain this information will require an eye-watering number of requests across the internet.  There are also obvious implications for the time that would be taken and the consequent apparent responsiveness of any app presenting this information.

Indeed as of version 0.26.0 of the SA API over 100 calls were required.  This is bad enough but HMRC has an undocumented throttling policy in place.  At the time of 0.26.0 it proved impossible to obtain a full set of ‘self-employments’ for a given UTR for a specific tax year.  This is clearly odd.  Clearly either HMRC have not tested this or it has been tested on a system with no throttling and no latency.

We do not know if other developers hit these problems but we raised the issue with HMRC.  Ultimately after a lot of polite grumbling we obtained a meeting with the SA Devs and SDS.  This resulted in changes being introduced.  In 0.38.0 it is possible to obtain much more information with fewer calls.  This is accomplished by embedding much of the content rather than requiring links to be followed.

Let’s accept HATEOAS and HAL, how do you set about discovering the Graph?  The HMRC documentation does not provide a formal statement of any of the nodes.  There are examples but it would be foolhardy to rely on the examples for completeness.  So the only option is to exercise the API.  But this is bizarre,  surely the point of HATEOAS and HAL is to provide a means of dealing with a dynamic Graph.  But, but SA is not like this.

If HMRC wish to use HATEOAS and HAL a way of describing the structure of the Graph needs to be found.  In addition a way needs to be found to allow metadata to be provided so that a caller can get a subset of the required Graph.

**Comment by alexec** [comment]
Hi Chandra, can you please reply to Andy?

**Comment by sudoku007** [comment]
Hi Andy,

I am one of the Dev's on SA API, appreciate the detailed analysis and feedback provided on the implications on using HATEOS and HAL like the vast no of calls, throttling, latency, 
responsiveness etc.

As you mentioned we already made few changes to embed subset of information along with self links which reduces the number of calls.

We are still brainstorming on ways to improve our API and try our best to address your suggestions in the future.

Regards,
Chandra
