### ISSUE TITLE
RAML please

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#219]
The RAML doc(s) for this api are missing from this repo.

**Comment by alexec** [comment]
Hi Andy, 

We do not currently have RAML for this API. This might appear sometime in the future.

Alex

**Comment by andyws** [comment]
Hi Alex,

I hope you are well.

I attended an HMRC session on 23rd September and was shown an evolution of the dev site and told the docs were generated off of RAML docs.  The output looked like the standard stuff emitted by RAML tooling.  I was curious to see how the HATEOAS api had been represented in RAML.

While waiting for the next SA Release I have been toying with the idea of writing something to capture the datamodel from the HATEOAS SA api but I'm concerned that such an effort would be a waste of time because of insufficiant info around completeness, optionality and value ranges.

**Comment by sudoku007** [comment]
Hi Andy,

I am on the Dev's on SA API, I will try to find and get back to you with the RAML which you were shown on the HMRC session.

Regards,
Chandra

**Comment by andyws** [comment]
Thanks Chandra.  I appreciate your help.

**Comment by P-Tracy** [comment]
Hello @andyws 

We don't use RAML at IRIS, but are you saying there's a simple way to reverse engineer the resource model or data model from the RAML document?  

To date, I have been hand crafting the resource model diagrams from the APIs to ensure our tax experts can understand and review them.  It makes a huge difference and means they can spot issues within a few minutes of discussion rather than trying to make sense of the URLs.

Any advice appreciated

**Comment by andyws** [comment]
Hi @P-Tracy,

I have been quite outspoken expressing the view that HATEOAS _alone_ is not appropriate for the SA API.  See my post at: [https://github.com/hmrc/self-assessment-api/issues/191](https://github.com/hmrc/self-assessment-api/issues/191).  

IMHO the most appropriate uses of HATEOAS are in situations where the resource/data model you are working with is dynamic/volatile in the short/medium term.  This is simply not the case with SA.  Unless HMRC lock down the data structure a consumer(US) would be foolhardy to reverse out the schema from an instance.  If HMRC is prepared to lock down the schema HATEOAS is not appropriate as all it adds is an opaque layer of indirection.

So I have pressed for a Swagger doc.  HMRC have, both in SA and in some other API projects, elected to use RAML.  This is perfectly reasonable and welcome.  There are some really good tools out there for  generating Swagger from RAML and vice versa and for generating clients and server stubs.  

**However the RAML does not represent the HATEOAS api**.  Rather it is an alternative api and currently does not yet( but will I'm sure in time ) fully capture the functionality of the HATEOAS api.

You could in principle document a HATEOAS api in RAML or Swagger but IMHO you would have to ask why bother?

For me the introduction of RAML has been liberating.  I can generate Angular2 and C# clients and WebAPI and Core servers which then allow me to test my code independently of the very limited sandbox and the very suspect application level throttling policy which makes testing at scale impossible.

I hope this helps and I'm very happy to discuss this or any other facet of this endeavour!

Regards
Andy

**Comment by P-Tracy** [comment]
Hi @andyws 

Thanks for that.  We too use Swagger, but we're having some issues rendering the RAML docs in Swagger, but I'm sure we'll get there.  I do often find a lot of my struggles are 'user error'!  

I'm still struggling to some degree with the API structures and content as opposed to the HATEOAS aspects.  Walk before you can run, in my opinion.  But I do see your points.  Your other post was very interesting.  Have you had much feedback on that?  Are you aware of any conclusions being reached with respect to the approach?

**Comment by andyws** [comment]
I like to think, modestly, that the arrival of the RAML documents was in part down to me ...

**Comment by GlassAndOneHalf** [comment]
I'm going to close this issue due to inactivity. Please open another if you would like to discuss this further.

Thanks,
Jacob
