### ISSUE TITLE
How to specify the summary's period

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#221]
We need clients to specify the period of time a summary was collected. We call this the summary's "period". 

The start date and end date of the summary must be within the business's accounting period. 

```
accountingPeriod.startDate <= period.startDate <= period.endDate <= accountingPeriod.endDate

period.endDate < now 
```
# Option 1

To create a summary (e.g. income), you POST:

```
POST /self-assessment/{utr}/self-employments/{sourceId}/incomes
{
  "type": "Turnover",
  "amount": 10.00,
  "startDate": "2016-09-01T00:00:00",
  "endDate": "2016-10-01T00:00:00"
}
```

Once you are finished updating HMRC, then you need to send a message to tell us that the update is complete:

```
POST /self-assessment/{utr}/self-employments/{sourceId}/completions
{"endDate": "2016-10-01T00:00:00"}
```

This will trigger a tax liability calculation.
# Option 2

Period is an entity in the resource model:

```
+-----------+
| Period    |
|-----------|
| id        |
| startDate |
| endDate   |
+-----------+
```

To updated HMRC, you create a period:

```
POST /self-assessment/{utr}/self-employments/{sourceId}/periods 
{
   "startDate": "2016-09-01T00:00:00",
   "endDate": "2016-10-01T00:00:00"
}
```

This will return an ID `periodId`:

For each item of summary data, you POST

```
POST /self-assessment/{utr}/self-employments/{sourceId}/periods/{periodId}/incomes
{
  "type": "Turnover",
  "amount": 10.00
}
```

Once you are finished updating HMRC, then you need to send message to indicate the period is completed:

```
 PATCH /self-assessment/{utr}/self-employments/{sourceId}/periods/{periodId}
{"complete": true}
```

This will trigger a tax liability calculation.

**Comment by alexec** [comment]
@saurabharora80  - would you like to review?

**Comment by P-Tracy** [comment]
Hi Alex

Not sure if this is resolved, but I can't see how Period as a discrete resource would work?  It's entirely associated and shares the same lifecycle as the resource it's hanging off, and would you be able to create a source without a period?  

By separating it out as a resource in its own right, it infers you can create this type of source without the period - or that the period can change independently of the values.  And I don't think that's the case?

**Comment by alexec** [comment]
Thank you Tracy.

It is our plan to change the API so that each source of income spans many tax years. You would be able to create it would doing an update. You could also change the source outside of the update.

The period would have it's own lifecycle, created at the start of an update process and finalised at the end of the update. 

We're are interested in understanding if one of other of these approaches work better for you.

**Comment by P-Tracy** [comment]
Hi Alex

I'm so sorry but I honestly don't understand what you're saying here.  Have you a sequence diagram or workflow of the scenario you're talking about?  

I don't understand how a source of income can span multiple tax years and be credited across tax years unless it spans accounting periods which are not aligned with tax years.  Which I thought was oos for MTD at the moment?  Tax is not really my thing so I will send this on to my tax BAs and ask if this makes sense to them.  

However, when we talk about 'process' in API terms, given it's entirely stateless, wouldn't the process have to be managed by explicit state transitions on the entity itself?  In which case there's a missing attribute or resource?  

As I said, I'm struggling to understand the use case so my questions may not be relevant.

**Comment by PaulOnions** [comment]
Where is the intelligence going to sit as to which update periods are within which Accounting periods and therefore affect which tax year computations? You should not be able to create a period without a source or a source without a period otherwise you cannot know which tax year the data will relate to.

**Comment by andyws** [comment]
There appear to be a number of 'periods' and the relationships between them are not clear ( to me ):

- Accounting Period

- Source Period

- Summary Period

- Tax Year

- Update Period ?

Is there a specification of terms available for Source/Summary/Update 'periods'?

**Comment by alexec** [comment]
I've updated the description to try and make the question clearer. I'll get back to you on your questions.

**Comment by P-Tracy** [comment]
Hi Alex

Thanks for that.  I'd say you may have opened a can of worms with your latest update as now I have a million questions about how we're managing the state machine internally!  

I don't think you're likely to get an answer to the question without providing the context and thinking around this workflow you've designed.  As far as I'm aware, this is the first time that you (MTD or HMRC) have mentioned state transitions, and I won't deny that 'Periods' was not the first time I expected to see this.  I can't even imagine what the state machine around a period resource would be - given it's two dates?  

I'm afraid I think this is bigger than something we can resolve on here.  Is there any documentation on the overall design of this?

**Comment by P-Tracy** [comment]
I can't really get my head around how a period can have a state; isn't it the summary that has a state and the period is the time-frame that the data and indeed state within the summary refers to?

Anyway, let's say a period has a state.  And go on the presume that it can be open -> active -> complete or a lifecycle like that.  Wouldn't the period resource then have to contain this state attribute?  So that when we retrieve it, we can know what state it's in?

**Comment by andyws** [comment]
A period as defined in RAML v2 is a complex type just much like a date.  I cannot see the value in constructing a model in which it is an entity in its own right.

**Comment by alexec** [comment]
Thank you for your feedback.

**Comment by alexec** [comment]
Mohin @WK:

> It feels like option 2 is the better choice since you know exactly against which period you are sending data, with option 1 I think it is very easy to end up with periods that don’t align, such as for a resource you might populate the time by mistake and for the other not
