### ISSUE TITLE
Capturing balancing charges, goods and services for own use, private use adjustments

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#223]
We currently capture these as summary level values:
- balancing-charges
- goods-and-services-for-own-use
- private-use-adjustments

This allows multiple values to be sent, that are added up in the calculation. Does your software collect these items in that way, or does it collect it as a single whole year values?

**Comment by andyws** [comment]
We maintain distinct values

**Comment by P-Tracy** [comment]
Hi Alex

We maintain discrete values too.

Also - I have raised this as a separate question, but our team were asking:
1. Why is Goods & Services Own Use pulled out as a separate resource as opposed to being a type of Expense?
2. Why does Goods and Services Own Use not have a 'type' attribute?  Wouldn't it have the same structure as Expenses, so the consumer can say what each item represented? 

Many thanks

**Comment by alexec** [comment]
Can I please ask - would you prefer to bundle them with income or expenses, or would you prefer to be able to update them separately?

**Comment by P-Tracy** [comment]
I think the BAs thought it would make more sense if the G&SOU was a type or sub-resource of expense (not income).  

My grip on tax is tenuous, but in our session, the discussion was around the fact for example, you buy £80 worth of petrol and £30 is business expense, but £50 is own use.  It's like a sub-category of the expense I think.

However, like most things the API reflects the business and tax is not what I do so I think this might be one for you to send out to the business analyst or product owner community?  (Who I don't think will be up for using GitHub)

**Comment by alexec** [comment]
Thank you for your feedback. We'll be updated with a new API specification soon.

**Comment by alexec** [comment]
Mohsin @ WK:

> Currently we do both in our online application I expect there will be other places where HMRC requires summaries and we have to capture details, hence I don’t think it matters to much for us if we need to send a summary or multiple records here
