### ISSUE TITLE
Test non-technical question 

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#230]
This is a test question to verify the process of passing non-technical queries to SDST.

**Comment by alexec** [comment]
@sudoku007 - I'm away tomorrow, could I please request (as Github triage) you chat to Scott about working through our process  (see https://confluence.tools.tax.service.gov.uk/display/MTE/Third+Party+Vendor+%28API+Consumer%29+Developer+Support)? Thank you!

**Comment by sudoku007** [comment]
Thank you for your enquiry.  Github issues are for developer's technical questions and suggestions so we have forwarded your issue to the relevant team.  They will be in touch shortly

**Comment by alexec** [comment]
@sudoku007 - any update?

**Comment by alexec** [comment]
@GlassAndOneHalf - can you check with SDST to see if their Github account can work now?

**Comment by alexec** [comment]
Closing this issue due to lack of progress.
