### ISSUE TITLE
Agent Authentication User

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#237]
Hello

We just received the comms that agent authentication is ready for test on the Live platform.  Can HMRC provide some credentials for us to test this with?

Thanks
Pauline

**Comment by sudoku007** [comment]
Hi Pauline,

Thanks for your query, will check our team on what comms went out and will get back to you with the answer.

Regards,
Chandra

**Comment by rakeshavasarala** [comment]
Hi Pauline,

Our team have been advised that the Agent authentication communication which was sent out is about the 'Married Allowance API' that is now in production and can be accessed by individuals or agents.

MTDfsB Self Assessment API's https://www.tax.service.gov.uk/api-documentation/docs/api#self-assessment-api are NOT yet enabled for Agents.

Regards
Rakesh

**Comment by GlassAndOneHalf** [comment]
I'm going to close this issue due to inactivity. Please open another if you would like to discuss this further.

Thanks,
Jacob
