### ISSUE TITLE
Agent Authentication - Sandbox

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#238]
Hello

Is agent authentication on Sandbox or just Live?  If not on Sandbox, can we get it put up there?  

Is the Sandbox -> Live progression still your deployment model?  Is this just an anomaly?

Thanks

**Comment by sudoku007** [comment]
Hi Pauline,

Thanks for your query, will check with our team on what comms went out regarding agent authentication and will get back to you with the answer.

Regards,
Chandra

**Comment by rakeshavasarala** [comment]
Hi Pauline,

MTDfsB Self Assessment API's https://www.tax.service.gov.uk/api-documentation/docs/api#self-assessment-api are NOT yet enabled for Agents.

Regards
Rakesh

**Comment by leehawksworth** [comment]
Hi Pauline

I believe you’re referring to the 'Marriage Allowance API now in production' email from SDST on 20th October. That email informed software developers that 'the Marriage Allowance API is now open to both Individuals and Agents to use in our Live production environment' - https://developer.service.hmrc.gov.uk/api-documentation/docs/api#marriage-allowance
 
There are currently no credentials to test this with, other than the sandbox environment. It would be helpful to understand what you need. Please feed this back using the 'Get help with this page' on the MA API documentation and the team will pick this up. 
 
Agent authentication is live for the Marriage Allowance AP. This is the first API we have made available to agents as we roll out agent authentication across our APIs. When an agent credential is presented, we check that the appropriate agent:client authority is in place. This API was previously in sandbox and, generally speaking yes, our deployment model is sandbox > live.

Thanks

Lee

**Comment by P-Tracy** [comment]
Hi Lee

Thanks for that.  

Is there any communication process for letting consumers know what's happening on Sandbox?  Did everyone else know that the agent authentication was available for test in Sandbox?  I know we didn't - but I fear we may not be on the correct mailing list?  We've been waiting for this for quite a while and would have leapt at the opportunity to test it, but I wasn't aware it was there.  

I've asked the development team to test the Sandbox version and we will get back via the hub if we experience any issues.  

As an aside, it would never have occurred to me to use the 'Get help on this page' link as I presumed that was issues with the documentation or the page itself.  We've been submitting feedback on the Feedback button at the top of the page - is this not correct?  

Thanks

**Comment by leehawksworth** [comment]
Hi Pauline

We emailed all subscribers to the 'Marriage Allowance API'. Plus we emailed all known 'Self Assessment developers'. Let me give you a call and we can check we have the right contact details for you.

'Get help with this page' can be used when you need some assistance in completing your 'task', 'feedback' is more general and can be used to say what you think about the service. 

Thanks

Lee

**Comment by P-Tracy** [comment]
Hi Lee

I've had a chat with some of our team in here, and we have only one user that we can test with on Sandbox - 'User1'.  But this is an individual as opposed to an agent who would allow us to test agent auth.

Can you let me know what agent user we can test with on Sandbox?  Is there documentation about this somewhere?  I notice the testing page doesn't seem to have been updated?  

What I would really like to know is:
1. What is the username and password for the test agent?
2. What UTRs does this agent have access to?
3. What is the distinguishing feature of each UTR?  i.e. what can I test using one over the other?

I want to ensure we are able to test the security aspects of the MA API as well as the positive scenarios, so I want to be able to throw UTRs at it and ensure our software can accommodate the 403 responses.   But also verify the API is throwing the correct 403 where appropriate.

Many thanks
Pauline

**Comment by andyws** [comment]
I have never been informed that there was a means of testing as an agent in the sandbox.

**Comment by leehawksworth** [comment]
Hi Pauline

No agent credentials are currently available to test against, but this is one of our priority backlog items, providing you with a richer test environment. 

Thanks

Lee

**Comment by P-Tracy** [comment]
@andyws do you need to support the ability to have individuals and agents interacting with your software?  If so, then yes the current OAuth flows can support it for Marriage Allowance only, so pre-population.  Self Assessment will implement the same solution, they just haven't rolled it out to those APIs yet (as far as I'm aware) so they remain individual-only

Where we're struggling is in getting the credentials for a test agent so we can verify this before we go live.  As Lee says though, it's on the backlog so should be with us soon.

**Comment by andyws** [comment]
@P-Tracy we have tested individual and agent access in production as of last week.  However we have not as yet been able to test it in the sandbox.

**Comment by P-Tracy** [comment]
@andyws - can I just check, did you use live agent credentials while testing in Live then?  So it was an active agent user?

Do you have access to a test agent user that you can test with in Sandbox?  You just didn't know it was available?

**Comment by andyws** [comment]
We used live credentials...our own

**Comment by GlassAndOneHalf** [comment]
I'm going to close this issue due to inactivity. Please open another if you would like to discuss this further.

Thanks,
Jacob
