### ISSUE TITLE
Is the Sandbox code 0.38?

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#239]
Is the Sandbox code 0.38 or has it been amended?

Specifically wrt the response to Discover Tax Year[ GET /self-assessment/{utr}/{tax-year} ] was there a change from 'liabilities' to 'liability'?

**Comment by rakeshavasarala** [comment]
Hi,

The latest version in production sandbox and the 3rd Party Integration Test environment is https://github.com/hmrc/self-assessment-api/releases/tag/v0.61.0.

I have updated the git and the changelog to reflect the same.

**Comment by alexec** [comment]
Can close?

**Comment by andyws** [comment]
Just to be clear was 61 marked as pre release and amended this morning to release?  I accept I might have missed 61 being release but I am surprised.

**Comment by rakeshavasarala** [comment]
Yes. The git tag was edited today.
The communication regarding the 3rd party integration test environment which was sent to MTD private beta developers should have also mentioned clearly that documentation on API Developer Hub and production sandbox endpoints will also be updated.

From now on, any breaking change or enabling of new features on production and integration test environment will be properly communicated.

**Comment by andyws** [comment]
@rakeshavasarala.  Thanks for clarifying that.

Can you clarify an additional set of questions.  

I was certainly on the initial private beta which looked at the OAuth2 mechanism.  Post a conversation with an 'important' fellow at the dev meeting at Dover House on 23rd September I am no longer convinced that I am still on the program.  

Q1: Am I on the current private beta?
Q2: If I am not on the current private beta, what if anything will I not have access to, which members of the private beta have access to? Documents, support, additional test environments et al?

**Comment by rakeshavasarala** [comment]
Hi,

I have asked SDST to confirm 
 - if Wolfsmart Ltd's are part of Making Tax Digital(MTD) Private Beta and 
 - if MTD communications are sent to you. 

I will update once I have more info.

**Comment by andyws** [comment]
Assuming we are not part of the private beta can you at least **_outline_** the range of documents, code and other info provided to members of the private beta which would not be available to non members?

**Comment by andyws** [comment]
Can you inform me whether the breaking changes (0.38 -> 0.61) were communicated to anyone outside HMRC?

Would it be easier if I made this an FOI request?  For an open source project you come across as remarkably opaque.

**Comment by GlassAndOneHalf** [comment]
Hi Andy,

@rakeshavasarala is currently in discussion with our software development support team to try to get Wolfsmart Ltd added to the private beta. As you are outside of the private beta, you will not receive any communications related to the Making Tax Digital project. I will follow up with Rakesh today to try and get you an update. 

Thanks,
Jacob

**Comment by GlassAndOneHalf** [comment]
Hi Andy,

You can see the latest changes in our change log, which contains some information about the breaking changes we have made: https://github.com/hmrc/self-assessment-api/blob/master/CHANGELOG.md

In 0.61, the GET liability endpoint was changed to no longer take an identifier. You may now only retrieve the latest liability calculation.

We have also developer documentation available, however this is currently limited to private beta participants only. Could you please send an e-mail to SDSTeam@hmrc.gsi.gov.uk requesting access to the private beta? You will need to provide your company name in addition to the IP addresses that you intend to use when communicating with our services.

Please do let me know if you have any issues.

Thanks,
Jacob

**Comment by andyws** [comment]
Jacob,

Thanks for the feedback.  I have done as you suggested and communicated my frustration and annoyance to SDS.

**Comment by GlassAndOneHalf** [comment]
Hi @andyws, have you received any communication back from SDST? If so, do let me know so I can close this issue.

**Comment by andyws** [comment]
I have heard nothing.  

I would prefer this to remain open for now.

**Comment by GlassAndOneHalf** [comment]
Hi @andyws I have been informed that SDST has messaged you asking for further details - can you confirm this is the case?

**Comment by andyws** [comment]
Hi Jacob,

Yes I heard from Martin yesterday evening.  I have supplied a list of IP addresses to be added to the whitelist.

So this issue can be closed.

Andy
