### ISSUE TITLE
RAML Issues

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#242]
I have previously patched the raml files when converting them to swagger2.  However I thought I would draw your attention to two common issues. 

1) A number of apis do not have an responses defined.

2) There appears to be an issue with the security.raml file but this may reflect differences between raml and swagger2.

[self-assessment-api-granularity-level-3-v2.errors.json.txt](https://github.com/hmrc/self-assessment-api/files/552981/self-assessment-api-granularity-level-3-v2.errors.json.txt)
[self-assessment-api-granularity-level-2-v1.errors.json.txt](https://github.com/hmrc/self-assessment-api/files/552982/self-assessment-api-granularity-level-2-v1.errors.json.txt)
[self-assessment-api-granularity-level-3-v1.errors.json.txt](https://github.com/hmrc/self-assessment-api/files/552983/self-assessment-api-granularity-level-3-v1.errors.json.txt)

**Comment by alexec** [comment]
Hi Andy,

I'll try and take a look at this in the next few days. 

So I can make sure that it's fixed correctly, can you tell me how you discovered these errors?

Alex

**Comment by alexec** [comment]
I should probably caveat this, we're using the RAML as a mechanism of discussion, but it not really intended for consumption or code generation.

**Comment by andyws** [comment]
Alex,

I have to say I really think your production of a raml or swagger spec is profoundly important.

Witness my recent experience with 0.61.  Unless my tests revealed it I would not in any practical sense be able to find out that 'liability' had become 'liabilities'.  Worse there may be other changes that I have missed.  This is a nightmarish situation and I am puzzled that other devs have not encountered similar issues.

Regards
Andy



-------- Original message --------

**Comment by andyws** [comment]
Alex,

The issues were exposed using Lucybot and nswag to transform the raml to swagger.

Regards
Andy

**Comment by alexec** [comment]
Thanks Andy,

I've fixed the missing "responses". The `security.raml` looks correct based an a few examples I've looked at, for example:

https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md

I think this could be a bug in the conversion process?

Alex

**Comment by andyws** [comment]
Thanks.  l'll check this out on Monday.

Agree re OAuth.

Regards
Andy

**Comment by alexec** [comment]
Raised issue: https://github.com/lucybot/api-spec-converter/issues/111

**Comment by alexec** [comment]
Hi Andy - we'll be creating a new RAML shortly. I'll update you soon.
