### ISSUE TITLE
Capturing allowances and adjustments

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#244]
The current and proposed APIs (for levels of granularity) allow you to send one value per-tax year for allowances and adjustments. This is in contrast to income and deductions that are captured as zero or more values per quarter. 

Consider these two examples:

~~~
PUT /self-assessment/nino/{nino}/allowances/{taxYear}
{          
   "allowancesOnSales": 10,
   "annualInvestmentAllowance": 10,
   "businessPremisesRenovationAllowance": 10,
   "capitalAllowanceMainPool": 10,
   "capitalAllowanceSpecialRatePool": 10,
   "captialAllowances": 10,
   "enhancedCapitalAllowance": 10,
   "restrictedCapitalAllowance": 10,
   "allowanceForSmallBalanceOfUnrelievedExpenditure": 10
}
~~~

~~~
PUT /self-assessment/nino/{nino}/adjustments/{taxYear}
{
   "accountingAdjustment": 10,
   "adjustmentToProfits": 10,
   "averagingAdjustment": 10,
   "basisAdjustment": 10,
   "includedNonTaxableProfits": 10,
   "lossBroughtForward": 10,
   "outstandingBusinessIncome": 10,
   "overlapReliefUsed": 10
 }
~~~
Note: not all allowances and adjustments are valid for all sources of income.

This method is suitable if your software captures single values for tax years. If your software captures multiple values (e.g. at a specific point in time) per quarter, then capturing that data as a summary for a period of time might be more suitable.

For example (using an API granularity level 1):

~~~
POST /self-assessment/nino/{nino}/periods
{
   "from": "2016-10-01 00:00:00",
   "to": "2016-11-01 00:00:00",
   "adjustments": {
      "accountingAdjustment": 10,
      "adjustmentToProfits": 10,
       "averagingAdjustment": 10,
       ...
   },
   ...
 }
~~~

Bearing that in mind, could you please review the above example and let us know how you'd prefer?

**Comment by alexec** [comment]
@P-Tracy, @bikezilla, @andyws, @PaulOnions - I'm not sure if you get automatic notifications, so I'm mentioning you here so you are aware of this question.

**Comment by P-Tracy** [comment]
Hi Alex

Not sure I understand the question.  You're just asking what format we want?  

In the first one, it takes an explicit tax year in the URL and in the second it takes two random dates.  Ultimately it's of no significance to me whether we go with option 1 or 2.  However, from your perspective the level of validation and error management in option 2 is significantly higher.  

HMRC then needs to validate and verify the date ranges provided and ensure they wholly fit into one tax year?  
You also need to ensure you don't have any existing allowances or adjustments with dates that overlap the new dates provided?
What is the behaviour if the dates provided only cover a portion of the tax year, so maybe 9 months instead of the full 12?  Is the remaining 3 month assumed to be 0?

At the end of the day, we will conform to the API you ask us to - we have all the data at hand and can massage it into any format.  

In my opinion, the contract should be wholly owned, defined and dictated by the level of intelligence and complexity that HMRC are able to accommodate.  In a perfect world ALL of the intelligence would sit with you, but given it's November and this needs to be live by April, I'm assuming there needs to be a level of pragmatism.

**Comment by PaulOnions** [comment]
Hi Alex,

I may be misunderstanding or over complicating here but...

There is also the issue that the consultation papers suggest you may be able to file adjustments either on a quarterly basis o wholly at the end of the year therefore you will need to cater for periodic filing with date ranges that you check for tax year fit and full tax year as well as the final filing at the end.

**Comment by alexec** [comment]
Hi,

You'll be able update HMRC of your adjustments and allowances whenever you like, either quarterly or end of year. 

By associated them with a tax year, we're saying that you set that value whenever you need to.

By associating them with a period of time, we're saying that they were specifically caused by events that the customer undertook in that period of time, e.g. related to a specify invoice or receipt.

Is that clearer?

Alex

**Comment by andyws** [comment]
@alexec 

Will updates be possible at any time or just once a quarter with a final set of adjustments at the year end?

**Comment by alexec** [comment]
Hi Andy - the minimum and maximum frequency of updates is a policy decision, so I'll pass your questions to SDST.

**Comment by P-Tracy** [comment]
Hi Alex

The frequency of the commits or state transitions is policy, but that doesn't necessarily align to the frequency of the submission.

If the state of an income was:

saved -> pending review (optional) - quarterly submitted -> submitted

This would mean we could submit the data to HMRC very regularly and there would be a specific submit where the data has been consciously reviewed and has been deemed ready for assessment or evaluation by HMRC.  

Without the states, at the moment it feels like everything is being submitted and set in stone from day one - which is worrying as we are submitting data quarterly that we don't know whether we can amend without causing alarm in HMRC.  It completely changes the behaviour of the consumer when using your APIs.

**Comment by andyws** [comment]
@P-Tracy 

Good question and speaks to my thought about providing a 'real time' view of tax liability given an amenable set of inputs.

**Comment by P-Tracy** [comment]
@andyws This was what my question about liabilities was relating to....  If none of my data is in submitted state, then the Liability is 'estimated'.  Same with if my data is only in 'Saved' or 'Quarterly submitted' state.

However, if I'm in 'Submitted' my liability would be definitive.

Without these states, given the infinite permutations for what a valid SA submission is, I just don't see how HMRC are going to be able to definitely say if the form has 'enough data' or not.  Without the User dictating the completeness of the data, how can we be sure they're finished.

The states are not correct as you want the Liability prior to submission, but I hope I've got my point across!

**Comment by alexec** [comment]
Thank you for your feedback. We'll be updated with a new API specification soon.
