### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#270]
Dear Developers,

We'd like your feedback on options for names within the API. Can you please indicate which is clearer, or perhaps suggest an alternative? Thank you.

# 1. 

| Resource Name | Path |
|-|-|
| `SelfEmployment` | `/self-employments` |

OR

| Resource Name | Path |
|-|-|
| `SelfEmploymentBusiness` | `/self-employment-businesses` |

# 2.

| Resource Name | Path | 
|-|-|
| `AnnualSummary` | `/2016-17` | 

OR

| Resource Name | Path |
|-|-|
| `AccountingPeriodSummary` | `/2016-17` |

**Comment by alexec** [comment]
@andyws, @P-Tracy, @PaulOnions, @bikezilla - we'd love your thoughts on this.

**Comment by PaulOnions** [comment]
I think Option 1 for Self  Employment and Option 2 for Accounting period summary.

**Comment by alexec** [comment]
Thank you @PaulOnions. We'll be looking into this further soon.
