### ISSUE TITLE
RAML 0.83

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#289]
Can you confirm that the following items are not publicly available on Github and will not be made available outside of HMRC for the 0.83 Release?

-   sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml

-   headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml

-   annotations: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/annotations.raml

-   types: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/types.raml

-   title: Versioning
    content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md

-   title: Errors
    content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

**Comment by GlassAndOneHalf** [comment]
Hi Andy,

This is correct - having spoken to the team responsible, these files will not be made public.

Thanks,
Jacob

**Comment by andyws** [comment]
It will come as no surprise that I am struggling to understand why these files are not being made available.  

Can you provide the contact details for the team concerned and if possible supply me with the reasons why these files are not being published?

**Comment by GlassAndOneHalf** [comment]
Hi Andy,

Could you please contact SDST about this? As these files are owned by another team there is little we can do to help you in this situation. 

Thanks,
Jacob

**Comment by andyws** [comment]
Hi Jacob,

Can you tell me the name of the team concerned.  I will then follow up with SDS.

I find this situation slightly bonkers/laughable as a version of at least one of said files is to be found on HMRC Github!

Regards
Andy

**Comment by GlassAndOneHalf** [comment]
Hi Andy,

The team you are looking for is the "API Platform" team. I hope this helps.

Thanks,
Jacob
