### ISSUE TITLE
Period dates

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#296]
Without obligations, are the software vendors to 'guess' the obligation dates through an accounting period plus 90 days algorithm and just hope it's accepted in the POST?

**Comment by dabd** [comment]
Thank you for your enquiry.
In the next release, you will be able to retrieve the obligation dates for a given source of income, so you won't have to compute them.

**Comment by P-Tracy** [comment]
Next release from the email was end Feb - but this was simulation or test only?  Is that the date you mean?

So we will make an assumption that this will be accessible to us by the time we go live for 5th April?

**Comment by dabd** [comment]
We are aiming to make a release next week/early February, in which we will provide a canned response so you can get the contract of the API and proceed with your development.

For April, we will provide a fully functional API to retrieve the obligation dates for a source of income.  I hope this helps.

**Comment by P-Tracy** [comment]
Thanks for that.  Yes, it does help.
