### ISSUE TITLE
Period date change

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#297]
There is a PUT on the Period resource (you call it periodic summary in the text but in the URL it’s a Period) but you can’t amend the dates on the PUT, only the financial data – is that correct?  And if so, why?

**Comment by GlassAndOneHalf** [comment]
Hi Tracy,

You are correct. We decided to make period dates immutable as the date ranges for period objects have business rules that must not be broken. A collection of periods must have date ranges that:
- Are contiguous (i.e. contain no gaps).
- Do not overlap with one another.

If we were to allow you to change the date range of an existing period, we would no longer be able to easily guarantee these properties.
 
For example, if you wanted to shrink the date range of a period, we would no longer be able to guarantee that the collection of periods for that user is free from gaps. Our recommendation would be to move the financial data into an existing period, or by creating a new period with the dates you require.

Thanks,
Jacob
