### ISSUE TITLE
Naming of resources in descriptions

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#298]
It’s really confusing to call something a word (periodic summary) when it’s actually the same noun as the singular version (period). It implies there are two resources when in reality there’s one. 

What you have is a GET, PUT and POST on Periods; where you GET a list or a singular resource depending on whether you supply a unique ID in the path or not 

There exists nothing called a Periodic Summary

**Comment by dabd** [comment]
Thank you for your feedback.  We are planning to do another round of user testing over the next few weeks which will be focussing on the API documentation and descriptions within the API to get your feedback and views.  We will certainly take into account your observations when we make the necessary changes.

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

Thanks for the suggestion! I have raised a ticket to look into this.
