### ISSUE TITLE
Obligation date calculation

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#299]
Are IRIS to calculate the Obligatory deadlines for our Customers based on a rudimentary accounting period plus 90 days? 

Initial response from SDS was:
"No, HMRC will determine and provide obligation dates based on accounting period"

My new response is:
"When? I need to be coding in earnest last week to meet our deadlines.  How can we design our flows based upon the promise of something we’ve never seen?  We were told about the Obligations last year but there isn’t even a design or an API available for us to code or design against."

**Comment by dabd** [comment]
I believe this is the same issue as https://github.com/hmrc/self-assessment-api/issues/296.
