### ISSUE TITLE
State transitions

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#300]
Chain so far:

Original Questions:
"The state change Alex mentioned in the session in December and is documented in the pack sent out by Sofia isn’t here; so there are no states on the periodic summaries? They’re all just finalised? "

SDS Response:
"This is to be decided when we analyse the end of year crystallization. "

PT Follow up:
"Can you see why this would be a problem for us?  We don’t know whether the thing we are designing to show our customer has 1, 2 or 15 possible states.  We don’t know if the data that goes to HMRC is seen to be finalised at the point of submission or via another user-initiated step.  How can we design flows that we won’t have to entirely rewrite when you have had time to analyse the end to end flow?  This could be dead development for us."

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

As this is a non-technical question, I have forwarded this to SDST for you. They will be in touch with you via e-mail.

Thanks,
Jacob
