### ISSUE TITLE
Unsubscribe - Private Beta scope expansion?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#301]
Original Question:
"If a User needs to change the Period dates, do they have to unsubscribe? "

SDS Response:
"If user need to change the Period dates, do they have to unsubscribe?’ – assuming ‘period dates’ refers to either ‘accounting period’ or ‘obligation dates’? If so no the customer won’t have to unsubscribe if they want to change their accounting period as a change of accounting period will be a change of circs which will trigger a change to the obligation dates in ETMP which in turn will be made available to the software. It is not possible for a customer to change their obligation dates in isolation – they are hard linked to the accounting period (at least for beta). "

PT Response:
"I was told that if a User needed to change their accounting periods they would be asked to unsubscribe.  It sounds as if this is no longer the case?  Has this changed, so the scope of public beta has been revised and expanded?  "

**Comment by GlassAndOneHalf** [comment]
Hi Tracy,

As in #297, period dates are immutable and can not be changed. I hope this helps!

Thanks,
Jacob

**Comment by P-Tracy** [comment]
Hello there

Not really.  This issue is around the unsubscribe process.  We must recognise that just because a date can't be changed via your exposed APIs, doesn't mean it doesn't need to be changed. 

What happens when someone needs to change their accounting periods - which is not an uncommon thing I am led to believe?  

I was told previously that this would trigger an automated unsubscribe process.  However, this response infers that 'unsubscribe' that was described to us at length in December is not common knowledge amongst all the teams.  And that a change to accounting period, and the trigger that would then change the obligation dates is not seen as something that cannot be supported for MVP.  

So this would infer that in the pipeline is an API that would allow for modifications to the core Self Employment data; a PUT on /self-employments?  But if this isn't there from day one, then surely we do need to support unsubscribe?  Or what is the solution?  

As usual, I am just confused about how this is all going to hang together and how we will support our Users through these disjointed processes.

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

Apologies, I misunderstood your question. As this is a business question, I have asked our BAs to have a look at this for you.

Thanks,
Jacob

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

As this is a non-technical question, I have forwarded this to SDST for you. They will be in touch with you via e-mail.

Thanks,
Jacob
