### ISSUE TITLE
Unsubscribe scenarios - documented list request

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#302]
Do you have a documented set of scenarios yet where the un-subscribe will be triggered? This is critical to IRIS in the design of our UX and in understanding the scope of our interactions with HMRC.

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

As this is a non-technical question, I have forwarded this to SDST for you. They will be in touch with you via e-mail.

Thanks,
Jacob
