### ISSUE TITLE
Unsubscribe flow - documented/description request

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#303]
Initial Question:
Do you know what the un-subscribe process is? I am slightly worried it’s not in the end February scope as it’s actually more important to us as software providers than the subscribe process. 

SDS Response:
‘unsubscribe’ – what are they looking at here? The ability for a customer to unlink their software? Or are they talking about cessation and how this will be handled? I think we need to understand better what software vendors need the answer to here. From a cessation perspective we are expecting to handle this manually in HMRC at least for MVP and early in the beta and put the customer back into the CESA system on death, emigration and insolvency – but is there something more the software feels it needs to do other than simply unlink? I think we would only need an unsubscribe functionality in the software when we automate the cessation activity. 

PT Response
Unsubscribe was mentioned for the first time at the Developer event in Leeds on the 13th December.  It was discussed in some detail.  We were told that for various ’unsupported’ activities, the User would be asked to unsubscribe from MTD.  I asked if this would be automated and was told yes.  I asked when it would be available in automated form, and was told April 2017.  I then asked for the full list of scenarios where one of our Users would do something that would take them out of scope of MTD – as clearly from a Usability perspective this is critical to us.  We also need to understand that this means we have to recognise not only IRIS Users who are not involved in Public Beta or those who are, but also those who WERE and no longer are.  And we need to understand what stages this can happen at, so that we can support our users in what is sure to be a very annoying situation if it happens 10 minutes before they were about to submit their tax return in the new format.

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

As this is a non-technical question, I have forwarded this to SDST for you. They will be in touch with you via e-mail.

Thanks,
Jacob
