### ISSUE TITLE
HATEOAS has gone?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#304]
None of the new API documentation shows the returning of linked responses. Have HMRC decided against using Hateoas? Or is it just in this version? Is it coming back? 

If so, obviously this is a major version change for all consumers, so again not ideal in my eyes as a consumer across multiple products.

**Comment by dabd** [comment]
We decided not to use HATEOAS/HAL in subsequent versions for two reasons:

1. At some point we realised that we did not have clear state change/scenario flows that would naturally follow the URLS presented in the HATEOAS/HAL responses

2. We received feedback from some third-party vendors who questioned using HATEOAS/HAL and were in favour of using JSON with no hyperlinks

However, we are open to reintroducing HATEOAS/HAL in the API if the users provide enough positive feedback.

**Comment by andyws** [comment]
As I am probably one of "vendors" referred to I would like to clarify my position.  

I have no issue with HATEOAS as such.  

I do have an issue where the data model underpinning a HATEOAS scheme is left implicit and not provided in a machine readable form.  This is especially important where the data model is extensive and complex as is the case here.  

I did wonder why in this context where the data model is is not volatile whether HATEOAS was a particularly good fit.

I do have an issue where no facility is provided to select the graph of data required.  We then arrive at a perverse situation whereby HATEOAS which aims at being ultra flexible and dynamic has to be locked down (in terms of what is linked and what is embedded) to reflect a subset of expected data access patterns.

It is my opinion that OData would have been a far better choice in this context.

**Comment by dabd** [comment]
@andyws At the time we opted for HAL as a minimal implementation of hypermedia/HATEOAS, which would enable self-discovery of the API in its simplest form: through hyperlinks.  If we find it is beneficial to the users of the API to reintroduce HATEOAS into the API, we will consider other more feature-rich options such as the one you are suggesting.  Thank you for your feedback!

**Comment by dabd** [comment]
@P-Tracy @andyws I have raised a ticket to take into account your feedback.  Thank you for your suggestions!
