### ISSUE TITLE
What is your roadmap for the missing parts of the end to end process?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#305]
Initial Question:
The roadmap in the email (below)doesn’t state when the obligations or indeed the calculations will be available in live, instead it mentions they’ll be available in simulation from end February. What is the schedule for this as we would need to be very confident this will manifest before the quarterly deadlines – but also from a usability perspective this also means our Users can’t request liability estimates when they want, which would seem one of the only benefits of MTD during Public Beta. 

SDS Response:
A further API release is planned for the end of February and the current plan is to include: 
• Expanding the Get business and property information elements to include Business name and address as well as accounting period and accounting type. 
• Introduction of test stubs for the following: 
• Simulating the ability to get the customers update obligations for self-employment and property businesses 
• Ability to simulate sending an update on interest income information 
• Agent Access – simulating the check whether an agent is authorised to act on behalf of the taxpayer and sending an update on their behalf. 
• Subscription to MTD – simulating the check to find out if a customer has subscribed to MTD 
• Get calculation – providing a mock calculation response that aligns with the output that will be received from the strategic calculator once all the APIs are in place.

PT Response:
I did read this, as I had to in order to form the question.  My question was what does this mean?  When does it go live?  Is it 2 weeks between being available in simulation to being available in production or is it 2 years?  As far as IRIS are concerned, we need to know everything about your roadmap – this is our development effort and our development teams working on our live products.  We cannot suspend all activity on our product suite to anticipate things coming from HMRC, especially if the design is not specified in advance and there’s potential for us to have to redesign as well as integrate.

**Comment by GlassAndOneHalf** [comment]
Hi P-Tracy,

As this is a non-technical question, I have forwarded this to SDST for you. They will be in touch with you via e-mail.

Thanks,
Jacob

**Comment by SDST-HMRC** [comment]
Hi Pauline,
Sorry for the misunderstanding, detail was added to your question not as a response but as context to help with answer from our delivery team. Formal answer will be provided early next week. 
Thanks,
Dennis
