### ISSUE TITLE
Which Release(s) is/are documented on the Hub and in the private sandbox?

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#306]
Which Release(s) is/are documented on the Hub and in the private sandbox?

**Comment by andyws** [comment]
Is it 0.83 or 0.85?

I can see a tag for 0.83 but not for 0.85.

**Comment by dabd** [comment]
Thank you for enquiry.
The release documented on the hub and private sandbox is 0.85.0.  You can check [here](https://github.com/hmrc/self-assessment-api/releases) which is the latest release.

**Comment by andyws** [comment]
@dabd 

Thanks
