### ISSUE TITLE
Does Self Employment get created automatically?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#307]
There is a POST on self employment, but the data it contains is provided by the User during the subscription process.  

Is this resource created by the software vendors?  Or is it created by the subscription process and we only need to do a GET on this?

The issue I forsee is if it's create by software vendor as a result of free type by our Users, then what happens if this doesn't match with what the User provided during the subscription process?

**Comment by dabd** [comment]
Thank you for you enquiry.
We are aware of this issue and we'll get back to you on this later.
For now, we'll be providing a way to prime the test system such that any self-employment business and UK property is set up.  Is this helpful?

**Comment by P-Tracy** [comment]
Sorry, no.  

What does your final sentence mean?  In the test systems you'll configure it that the self employments are created for us?  That would only help us if that's what will happen on live, if not I'd rather you didn't and we muddle through with what will happen on live.

Do you know yet what the integration between subscription and self-assessment is?

**Comment by dabd** [comment]
Taxpayers must be subscribed to MTD to use the API, and as part of that process they must tell HMRC about their self-employment business, and if they have UK property. Therefore, the APIs to add a self-employment business/UK property business will not be available in live during private beta. 

So that you are able to test, we will provide a mechanism to add businesses - likely this API.

**Comment by P-Tracy** [comment]
OK - so we are to write the code to create the self-employments ourselves for our testing purposes.  But when SA integrates with Subscriptions, then this will be decommissioned?  

Do you know at what stage this will happen?  Have you got these cross-team dependencies in the roadmap for us to plan against?

We are of course trying to figure out our internal roadmap for development, test, integration test and release.  We won't be able to do that without knowing at what stage we need to stop creating the SE ourselves and to retest to ensure what we were creating ourselves via the POST is what is being returned during subscription.

**Comment by dabd** [comment]
As your last comment addresses a non-technical issue, I have forwarded it to the SDS Team, which will be in touch shortly.
