### ISSUE TITLE
Optional ID on List responses

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#312]
The developers have just pointed out that on all of the GET endpoints where a list is returned, the ID for each of the elements in the response is optional

We would really need this to be mandatory or we won't be able to call for the specific GET on the resource by providing the ID

**Comment by saurabharora80** [comment]
We are using the same json schema document for POST (create resource) and GET All (retrieve all resources) as it is essentially the same resource. 
Now the 'id' is _**not**_ required during the creation of the resource, but it is returned when all the resource are fetched via a GET, it is marked as optional in the json schema. 
I hope this alleviates the confusion. :)

**Comment by P-Tracy** [comment]
so it says it's optional but it will always be there?

**Comment by saurabharora80** [comment]
Yes... It would always be there in the GET All response.

**Comment by saurabharora80** [comment]
Hi Pauline,

Are you happy for me close to this issue? 

Thanks
Saurabh

**Comment by P-Tracy** [comment]
Hello Saurabh

Sure

thanks
