### ISSUE TITLE
NI numbers

### ISSUE THREAD

**Issue by dvdfmiller** [hmrc/self-assessment-api#313]
Hi,
When issuing a HTTP post for "Add a UK Property business" with a made up NI number I get this error:

{"statusCode":404,"message":"URI not found","requested":"/sandbox/ni/QQ123456C/uk-properties/"} 404

How can I get existing sample NI numbers to use for testing?

thanks
David

**Comment by saurabharora80** [comment]
Hi David,

Can you please provide the whole URL you used along with the host.

cheers

**Comment by dvdfmiller** [comment]
Hi Saurabh,
Thanks for your email.

Sorry I travelling at the moment but I'll send you the whole URL later 
today.

best regards
David

**Comment by dvdfmiller** [comment]
Hi Saurabh,
Requested info is:

URL:
https://api.service.hmrc.gov.uk/self-assessment/ni/QQ123456C/uk-properties/

addHeaders:
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer *************************

setEntity:
{"accountingType": "CASH"}

thanks
David

**Comment by saurabharora80** [comment]
Hi David,

Please use this base URL 'https://apisandbox.tax.service.gov.uk/selfassessment/' instead of 'https://api.service.hmrc.gov.uk/self-assessment/'. 
The usage of sandbox keys for SA APIs on the API Gateway has been deprecated. A communication was send it regards to this to all BETA developers by SDST last month. Please contact SDST for more details. 

cheers
saurabh

**Comment by saurabharora80** [comment]
Hi David,

Please use this URL "https://api-sandbox.tax.service.gov.uk/self-assessment/" instead of the of the one given in the previous message. I somehow managed to miss the hyphens (-) before. 

Cheers
saurabh

**Comment by dvdfmiller** [comment]
Hi Saurabh,
Thanks for this. I had corrected one of the missing hyphens but missed the other!

However I am getting the error when trying to add a UK property business with a POST:
https://api-sandbox.tax.service.gov.uk/self-assessment/ni/QQ123456C/uk-properties
{"code":"NINO_INVALID","message":"The provided Nino is invalid"} 400

And so what NI numbers do I use for testing?

Also can you confirm that for authorisation do I still use these URLs?
https://api.service.hmrc.gov.uk/oauth/authorize
https://api.service.hmrc.gov.uk/oauth/token

Any thoughts?
thanks David

**Comment by saurabharora80** [comment]
Hi David,

A valid NINO matches this format => "[[A-Z]&&[^DFIQUV]][[A-Z]&&[^DFIQUVO]] ?\\d{2} ?\\d{2} ?\\d{2} ?[A-D]{1}"
Please refer to this blog post => https://www.gov.uk/hmrc-internal-manuals/national-insurance-manual/nim39110

You can also generate a valid NINO by using "nextNino" method in 
https://github.com/hmrc/domain/blob/master/src/main/scala/uk/gov/hmrc/domain/Generator.scala

There is no Authentication and Authorisation on the api-sandbox, you don't need a valid Token.  

Let me know how you get along. 

cheers
saurabh

**Comment by dvdfmiller** [comment]
Hi Saurabh,
Yes that worked - very helpful.

My previous sample NINO "QQ123456C" was invalid on 2 counts: 
1) "QQ" is invalid
2) I needed spaces

And so I changed to "AA 12 34 56 A" and encoded in the URL like this "AA%2012%2034%2056%20A" and this worked.

I also changed the pattern match in Java to 
boolean nino.matches("[[A-Z]&&[^DFIQUV]][[A-Z]&&[^DFIQUVO]] [0-9]{2} [0-9]{2} [0-9]{2} [A-D]{1}")

Many thanks
David

**Comment by GlassAndOneHalf** [comment]
Hi David,

This should still work without using any spaces.

scala> val nino = "AA123456A"
nino: String = AA123456A
scala> nino.matches("[[A-Z]&&[^DFIQUV]][[A-Z]&&[^DFIQUVO]] ?\\d{2} ?\\d{2} ?\\d{2} ?[A-D]{1}")
res6: Boolean = true

Thanks,
Jacob

**Comment by dvdfmiller** [comment]
Hi Jacob,
Thank you.  I verified this also now.

best regards
David
