### ISSUE TITLE
3 line accounting

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#316]
Hello

Do the current set of APIs support 3 line accounting?  

Is the User to support income, a single expense of 'other' and then HMRC derive the profit?  

How does someone indicate that's what they're doing?  And haven't just populated the API badly?

**Comment by saurabharora80** [comment]
Hello Pauline,
We don't support 3 line accounting right now.

**Comment by saurabharora80** [comment]
Hi Pauline,

Are you happy for me to close this issue as well? 

saurabh

**Comment by P-Tracy** [comment]
Hello

Yes, that's fine thanks
