### ISSUE TITLE
generating ninos

### ISSUE THREAD

**Issue by forbescomputers** [hmrc/self-assessment-api#320]
having read a different issue you suggest

You can also generate a valid NINO by using "nextNino" method in
https://github.com/hmrc/domain/blob/master/src/main/scala/uk/gov/hmrc/domain/Generator.scala

Can you explain how to access this via the api.

I can access data using the AA123456A suggested by someone else but am worried this will cause conflicts.

**Comment by saurabharora80** [comment]
You cant access the Generator via the API; the only way to generate is to checkout the file from our public github (the path is given above.) and execute the method. 
The other way would be generate a NINO yourself which matches the pattern given in the other issue. 
You _shouldn't_ use AA123456A; instead generate your own unique one or else there could be a conflict.

**Comment by forbescomputers** [comment]
Could you generate me a Nino. I have no knowledge of Scala 

David Forbes

**Comment by forbescomputers** [comment]
Ignore that I will generate my own based on the pattern

David Forbes

**Comment by saurabharora80** [comment]
Hi David, 

We would hopefully have an API for generating test NINOs in our next release. A communication for the same would be send out if we manage to add it to the next release. 

Saurabh

**Comment by forbescomputers** [comment]
it is fine I am just generating them sequentially.


Forbes Computer Systems Ltd
Registered in England 2829879
