### ISSUE TITLE
Standardize the error objects

### ISSUE THREAD

**Issue by osblue13** [hmrc/self-assessment-api#321]
Currently there seems to be two different error objects returned as part of a 4xx error response:

1: 
```
{
  "code": "NINO_INVALID",
  "message": "The provided Nino is invalid"
}
```

2: 
```
{
  "code": "INVALID_REQUEST",
  "message": "Invalid request",
    "errors": [
    {
      "code": "INVALID_MONETARY_AMOUNT",
      "message": "annualInvestmentAllowance should be non-negative number up to 2 decimal values",
      "path": "/allowances/annualInvestmentAllowance"
    },
    {
      "code": "INVALID_MONETARY_AMOUNT",
      "message": "averagingAdjustment should be non-negative number up to 2 decimal values",
      "path": "/adjustments/averagingAdjustment"
    }
  ]
}
```

Are there any plans to standardize it, so that the error objects returned are the same model regardless of the error. i.e something like:

```
[
   {
      "code": "INVALID_MONETARY_AMOUNT",
      "message": "annualInvestmentAllowance should be non-negative number up to 2 decimal values",
      "path": "/allowances/annualInvestmentAllowance"
    },
    {
      "code": "NINO_INVALID",
      "message": "The provided Nino is invalid",
      "path": "" (optional)
    },
]
```

**Comment by saurabharora80** [comment]
Well, 
This is our standard error message; 
`{
  "code": "INVALID_REQUEST",
  "message": "Invalid request",
    "errors": [
    {
      "code": "INVALID_MONETARY_AMOUNT",
      "message": "annualInvestmentAllowance should be non-negative number up to 2 decimal values",
      "path": "/allowances/annualInvestmentAllowance"
    },
    {
      "code": "INVALID_MONETARY_AMOUNT",
      "message": "averagingAdjustment should be non-negative number up to 2 decimal values",
      "path": "/adjustments/averagingAdjustment"
    }
  ]
}`

You should create a single Error object on your side with fields such as 'code': String, 'message': String and 'errors': List[Error] where the errors list may be empty. Please refer to the JSON error schema on the hub for detail. 

I would much prefer the structure suggested by you, but we hamstrung the other APIs on the platform.

**Comment by andyws** [comment]
@osblue13 

Looking at the raml spec I would observe that there is just one definition of the error object and the two examples are both valid by that definition.

Generating the following C# (Typescript/JS also available) from the Json Schema shows this clearly:


```
namespace MyNamespace
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "8.1.6249.15627")]
    public partial class Part 
    {
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Code { get; set; }
    
        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Message { get; set; }
    
        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Path { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Part FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Part>(data);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "8.1.6249.15627")]
    public partial class Error 
    {
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Code { get; set; }
    
        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Message { get; set; }
    
        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Path { get; set; }
    
        [Newtonsoft.Json.JsonProperty("errors", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.ObjectModel.ObservableCollection<Part> Errors { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Error FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Error>(data);
        }
    }

```

For my own sanity I have given up trying to reverse out the data model from the documented and operational examples.  Better to rely upon the RAML, imperfect though it is.

**Comment by saurabharora80** [comment]
The generated code will be able to parse the first 2 error structures as both are correct.

**Comment by saurabharora80** [comment]
Are you happy for me to close this issue?

**Comment by andyws** [comment]
@saurabharora80 

It's a pity that the wiki isn't open to contributors so this stuff doesn't sink below the waves or get lost in one-to-one emails with SDS

**Comment by andyws** [comment]
But there again perhaps I spoke too soon...

In the application.raml file many of the errors are typed as:

```
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
```

But types.errorResponse is defined in types.raml as:

```
  errorResponse:
    properties:
      code: string
```

But some are typed as:

```
              403:
                body:
                  application/json:
                    type: !include schemas/Error.json
              409:
                body:
                  application/json:
                    type: !include schemas/Error.json
```

So in my opinion a version of this questions remains open.  **Why do we need two distinct error constructs?**

**Comment by saurabharora80** [comment]
`400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
`
This is API hub custom/non-standard RAML for generating error tables. Please don't refer to it.

**Comment by kaladin-storm** [comment]
Yes, happy to close.

Thanks @saurabharora80 @andyws
