### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#334]
Got this at 1725 this evening from SDS. 

`We have released additional functionality today to the MTDfB SA APIs for testing on the HMRC API Developer Hub.`

What is the Git tag for this release and the tag of the previous release?

**Comment by saurabharora80** [comment]
Hi Andy,

Please refer to the CHANGELOG.md for both.

**Comment by andyws** [comment]
So the current code available in the private beta is tagged 0.99.0 in Git correct?  But what was the previous version tag that this new code replaced?

**Comment by rakeshavasarala** [comment]
Previous version is 0.85.0

**Comment by rakeshavasarala** [comment]
Hi Andy,

version 0.100.1 was released today (06-Mar-17) to fix an issue with Add self-employments end-point
