### ISSUE TITLE
Mock Calculation

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#337]
In the email sent on Thursday you mention that there's access to:

"Mock Calculation - This will provide a static response showing the information that will be provided by the Calculator once we go live"

1. Can I just clarify that this means, irrespective of the data we supply in the build up to the requesting of the calculation, it'll just supply the same, canned response?  
2. If so, does this mean that the new test environment we were told would be available is not?
3. Or does it mean the new test environment is available, but calculations is not included in its scope?
4. And if either of the above, how are we to test the calculations prior to go-live?

Thanks

**Comment by saurabharora80** [comment]
Hi Pauline, 

Thanks a lot for taking the time to review our latest documentation. 

Please find below the answer to your question in order. 

Answer 1:  **Yes**. To begin with we will provide a canned response irrespective of the financial data provided. Eventually, (sometime in the coming months) this canned response would be replaced with actual computed response while maintaining the structure of the response. 
You would be informed of this switch (from canned to real computed values) beforehand. 

Answer 2/3: To begin with the new test environment called ETE (External Test Environment) would also provide a canned response. 

Answer 4: The structure of the calculation response is a part of the API contract and it would be **same** for both canned and real computed values. So for your tests you must verify that the response you receive via the calculation API matches the documentation. 

Saurabh

**Comment by P-Tracy** [comment]
Thanks for that

Can I just check this statement:
"To begin with the new test environment called ETE (External Test Environment) would also provide a canned response."
ETE is providing canned responses for calculations only?  It's providing stateful responses for all the other APIs?

**Comment by saurabharora80** [comment]
Yes, canned response for calculation **only**. All other APIs would be stateful.

**Comment by saurabharora80** [comment]
@P-Tracy can I close this issue?

**Comment by P-Tracy** [comment]
yes.  I guess so
