### ISSUE TITLE
Live Date?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#339]
In the email sent on Thursday, there's a lot of mention of 'when this becomes Live'.  Can we have the date that this is all due to be available in a Live environment please?

**Comment by saurabharora80** [comment]
@P-Tracy  We have forwarded this question to the relevant team. We will get back you shortly with the answer.

**Comment by dharma66** [comment]
This refers to an email received 'last Thursday'. Given the issue was opened 9 days ago, it seems like this refers to Thursday 2nd of March?
I don't seem to have any emails from SDSTeam on that date? It sounds like the email may have contained important information...?

**Comment by sudoku007** [comment]
Hi dharma66,

Will try to find what email was sent out on Thursday (2nd March?) and check why if it was not received by you. 

Regards,
Chandra
