### ISSUE TITLE
Obligation grace period?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#340]
In the released APIs the Obligation resource just contains the two dates; start and end.  

Is there no concept of grace period at the moment?  
Or should we communicate a grace period to Customers, but allow them a fixed period post end-date to submit their data?

**Comment by saurabharora80** [comment]
I have raised this to business. We should get back to you soon with an answer.

**Comment by saurabharora80** [comment]
Grace period is _1 calendar month_ after the end of each Obligation period. 
This should ideally be a part of the Obligation resource. We would see if we could have the backend provide this in the future.

**Comment by P-Tracy** [comment]
Yes, I agree.  It would make a lot of sense for it to be there! Would it take long to add it?  Are you expecting another API release before go-live in April?

Are HMRC expecting the vendors to add it in the interim while it's not there, or is grace period out of scope for MVP now?

**Comment by saurabharora80** [comment]
I am unable to provide a timeline on this feature release. 
For the time being we except the vendor to inform the users of the 1 calendar month grace period.

**Comment by P-Tracy** [comment]
OK.  Thanks

Is it possible to add this request/requirement to the Developer Hub documentation for Obligations?  As I'm aware when you close these issues none of the vendors who don't use Git or who aren't aware the question was asked will not know about this....

**Comment by saurabharora80** [comment]
I am not sure what you mean by "add this request/requirement to the Developer Hub documentation for Obligations"? 
I have raise a ticket on our internal board for this.

**Comment by P-Tracy** [comment]
Sorry @saurabharora80 

I meant, can you add to the documentation on the Hub what you've said here?  So grace period is a missing attribute of the obligation, but that it will always be one calendar month from end date so consumers can communicate this to their Users?

My worry is that when you close this issue, this piece of information which is quite useful disappears

**Comment by saurabharora80** [comment]
@P-Tracy we had a team discussion and we would prefer to provide the Grace period/Obligation due date via the Obligation resource. Adding it the documentation may lead developers to build the logic in their application, and we would like to avoid that duplication. 
So for the time being we would not be adding this to our documentation but rather change code to provide it via Obligation resource.

**Comment by P-Tracy** [comment]
@saurabharora80 

Makes perfect sense to me.  I'd rather you did it too as then you can change it when you please....

Now..... next question ..... before April MVP release or after, do you think?

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

We will forward this issue to the business, but I can't currently provide you with any timescale for when this might be changed. We have an internal ticket to track this issue and we will get back to you as soon as we have a rough idea.

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

We have received a response from the business. The data we are expecting to provide will be: 

> • The tax year the obligations relate to
> • The income source ie: property, business 1, business 2 etc
> • The obligation type ie Obligation/Crystallisation 
> • The dates the obligation covers ie from and to dates
> • The due date
> • The status of the obligation ie met 
> • The date the obligation was met

The due date will be the obligation "to" date plus the grace period.

Thanks,
Jacob
