### ISSUE TITLE
Gov-Test Scenario

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#341]
I noticed a new header in the API: Gov-Test Scenario, and the description refers to a Test Data Table.  

What is this?  
What can it do?
And who is it for - us or you?
If for us, when can we use it?

**Comment by saurabharora80** [comment]
@P-Tracy  This is help Third party developer (i.e you) simulate a few failure/error scenarios on Sandbox and ETE.  

This is close linked to #338. Please refer to that for more details.

**Comment by saurabharora80** [comment]
@P-Tracy can I close this issue?

**Comment by P-Tracy** [comment]
Yes, thanks
