### ISSUE TITLE
Mandatory Calculation?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#342]
Hello

Do we still HAVE to do a calculation request on or after the end of the obligation date so that HMRC knows that we have complied?  Or has that been resolved?

**Comment by saurabharora80** [comment]
Yes, you must provide the financial data for the whole obligation period **and** request a calculation to meet your Obligation.

**Comment by P-Tracy** [comment]
OK, thanks

I would really really really recommend when you release the API, you also release a standard workflow to navigate through it.  

Even though you are refining the structure and content of the Developer Hub, it still doesn't have anything useful in there about actual usage of the APIs.  All it would take is a Behaviour section that says POSTing of the tax calculation is a mandatory step for obligations to be met due to the HMRC implementation.  

I can't emphasise enough how this is NOT what we would have done had you not mandated it, and it's not obvious from the API that this is indeed mandatory.

**Comment by andyws** [comment]
I agree 100%

> Even though you are refining the structure and content of the Developer Hub, it still doesn't have anything useful in there about actual usage of the APIs. All it would take is a Behaviour section that says POSTing of the tax calculation is a mandatory step for obligations to be met due to the HMRC implementation.

> I can't emphasise enough how this is NOT what we would have done had you not mandated it, and it's not obvious from the API that this is indeed mandatory.

**Comment by saurabharora80** [comment]
Thanks for your feedback. I understand your concern with regards to combining obligation check with triggering of calculation. We would take this feedback to business.

**Comment by P-Tracy** [comment]
Thanks @saurabharora80  - I have moaned about that unfortunate coupling so much I think HMRC have tuned me out now !  :o)

But the point I was making was more to make sure you over-inform in the API documentation.  At the moment it reads as if you've all forgotten we have to build something from it.  Large pieces of critical workflow and transaction requirements are not clear or obvious or written down.  

It makes my life really really difficult and tiresome - when someone, somewhere in HMRC knows this and all they have to do it write it down and we'd all get that insight.

**Comment by saurabharora80** [comment]
We have added a paragraph about meeting the Obligations in our latest documentation which talks about the (unfortunate) coupling between calculation trigger and meeting obligation. 
I have included that snippet below.
"
To meet their obligations, taxpayers are required to submit regular financial updates for each of their businesses. Typically these updates cover four 3-month obligation periods, with one set of obligation periods per business per accounting period. To meet the taxpayer's obligation for a particular obligation period for a business:

- Supply summarised transactions for income and expenditure for the the whole of the obligation period for that specific business
- Request a tax calculation
"

Please advice what you think is missing from it?

**Comment by P-Tracy** [comment]
That text would help matters, but can I ask where you got that text?    I'm looking at the developer hub and I can't find that anywhere.

**Comment by andyws** [comment]
Given the following:

> To meet their obligations, taxpayers are required to submit regular financial updates for each of their businesses. Typically these updates cover four 3-month obligation periods, with one set of obligation periods per business per accounting period. To meet the taxpayer's obligation for a particular obligation period for a business:

> Supply summarised transactions for income and expenditure for the the whole of the obligation period for that specific business
Request a tax calculation

Would you please clarify whether triggering a first calculation in a 24 hour period will prevent a subsequent recalculation within the 24 hour period?

**Comment by saurabharora80** [comment]
@P-Tracy The text can be found in the 'Overview' section of our currently LIVE Documentation [here](https://www.tax.service.gov.uk/api-documentation/docs/api/service/self-assessment-api/1.0)

**Comment by saurabharora80** [comment]
@andyws I have raise a separate [issue](https://github.com/hmrc/self-assessment-api/issues/354) for this, as it goes beyond the scope of the original query.

**Comment by P-Tracy** [comment]
Thanks @saurabharora80 

I'm sure you hate me by now .... but that's really not where I would look to find that information, but that may just be me!

**Comment by P-Tracy** [comment]
feel free to close!

**Comment by saurabharora80** [comment]
@P-Tracy Interesting. Where would you like to see it?

**Comment by P-Tracy** [comment]
My automatic point of reference was the 'met' attribute on the Obligation response.  I expected it to describe what the behaviour of it was, and how it was switched from true to false.

I do keep moaning about the same things, but when an API has a boolean of 'word' = true/false, it is less than helpful for the description to say this:

"True if this obligation period has been met; false otherwise" as this is just a combination of the same words again - I can get that from the raw API and payload.

What I would look for here is what triggers is from one to other, and the associated behaviour.

I also have an outstanding question relating to the transition and how the consumer is made aware of the success/failure and the reason for the failure, but hopefully that would be answered separately (and then added to the 'met' description as a bonus) ......

**Comment by saurabharora80** [comment]
@P-Tracy your last question is linked to #343. It has been raised to TDG. Please watch #343 for updates.

**Comment by P-Tracy** [comment]
Yes, thanks!

**Comment by P-Tracy** [comment]
Feel free to close this one!
