### ISSUE TITLE
Why 'list SE Periods' test only?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#344]
Why is this not going live with the MVP?

We are relying on this as our MVP will only support people who have not supplied any Periods already for an obligation date range.

**Comment by P-Tracy** [comment]
Hi Alex

I think it's only the one I mentioned:

" List all self-employment update periods [test only]"

We are locking down our requirements for MVP to support only the basics, so we need access to this to ensure we can limit our scope.

**Comment by alexec** [comment]
Thanks Pauline. I'll raise this.
