### ISSUE TITLE
Release plan for 'test only'

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#346]
For the functionality that's in 'test only' is this guaranteed to be available prior to the end of the first obligation period?  

Are you yet able to publish a more detailed roadmap for iterative release of the functionality?

**Comment by forbescomputers** [comment]
It is not clear at all. Is [test-only] a permanent thing - or does it just not ready yet ?

**Comment by saurabharora80** [comment]
[test-only] is label for API which would be available in test environment, but not in MVP which goes LIVE in April. 
They will become available post MVP; The exact timeline for their release is a Delivery question which needs to answered by business. We have raise the question, and would get back to you shortly. 

Internal Use
[MTDSA-970](https://jira.tools.tax.service.gov.uk/browse/)

**Comment by forbescomputers** [comment]
It is quite important. With the API excluding [test-only] calls and
therefore the LIVE system as it stands there will be no facility to make
corrections if you realize you have submitted incorrect data.

It has also been reported in the accountancy media that HMRC are saying
that people involved in the live trial will potentially not need to submit
tax returns and the data is "real"

It will also dramatically change the agent/client interaction we were
envisaging.

Whether moving certain calls to [test-only] was a policy change or just a
delay is therefore critically  important.

If it is just a timing issue, knowing when the facilities to access data
and to make amendments is likely to come online will also affect how we
guide users.


Forbes Computer Systems Ltd
Registered in England 2829879

**Comment by sudoku007** [comment]
Hi forbescomputers,

The [test-only] label is only for the MVP as we it could not be delivered within the timescales of the MVP.

Post MVP the [test-only] will be remove in future and it will be available as a regular feature.

Regards,
Chandra
