### ISSUE TITLE
Is it still working ?

### ISSUE THREAD

**Issue by forbescomputers** [hmrc/self-assessment-api#349]
It was working before !

What URL should I now be using ?
Does it still automatically create a new record when I give NI number ?

C:\temp>curl -k -v -X GET -H "Authorization: Bearer 36d5cefb838220c735eb216220283bb" -H "Accept: application/vnd.hmrc.1.0+json" https://api.service.hmrc.gov.uk/self-assessment/ni/NL123456D/self-employments 

results in ....
{"statusCode":404,"message":"URI not found","requested":"/sandbox/ni/NL123456D/self-employments"}

**Comment by saurabharora80** [comment]
Please refer to https://github.com/hmrc/self-assessment-api/issues/313

**Comment by forbescomputers** [comment]
Thank you, but #313 is what I referred to some weeks ago and has been working. It has now stopped working.

Are there specific NINOs I need to use ? Any valid e.g. NL123456D has been working for me for a few weeks but no longer does.

Should I be using the api-sandbox.tax.service.gov.uk which has been working but now does not respond,
or api.service.hmrc.gov.uk which now has the mtd api and responds, for all services including agent-client-authorisation, but for self-assessment says resource cant be found for any nino I have tried. ?

**Comment by saurabharora80** [comment]
**_https://api-sandbox.tax.service.gov.uk/self-assessment/_** - This is the path to the SA sandbox API in AWS. This is a test only environment which can be used with **any well formed NINO**. (please see #313 for valid NINO format). 
_Also, its important to remember that data on this environment is **purged** every 2 weeks._  

**_https://api-sandbox.tax.service.gov.uk/self-assessment/_** - This is path to SA PROD API, which is behind the HMRC API Gateway. This is the LIVE/PROD environment which can only be used with **_real user NINO_** and correct level of Authentication and Authorisation. 

So, if you are only use our API for **testing/verifying the API contract**, please use the **former**. 

_Please try with new NINO and Let us know the exact API resource consumed and error encountered._

**Comment by forbescomputers** [comment]
I understand. I think the issue is that what was meant to be my fixed IP address seems to have changed which is why api-sandbox was hanging.

ps. There is a typo - in your response - you have repeated the URL.

**Comment by forbescomputers** [comment]
I have confirmed the issue was that I was accessing from a different IP.

**Comment by forbescomputers** [comment]
I would add that when accessing the "live" api with test credentials and a made up NINO the error message is not about authentications and refers to /sandbox/

**Comment by saurabharora80** [comment]
@forbescomputers thanks for the heads up on the typo. :) I have fixed it. 
"...refers to /sandbox/" that is expected as you must have been using the API HUB's 'sandbox' keys to access 'api.service.hmrc.gov.uk'. We have since moved the whole sandbox implementation to AWS and removed all "/sandbox/...." resources from our API.

**Comment by saurabharora80** [comment]
@forbescomputers can I close this issue?

**Comment by forbescomputers** [comment]
yes


Forbes Computer Systems Ltd
Registered in England 2829879

**Comment by osblue13** [comment]
@saurabharora80  Can the documentation be updated to reflect the correct test endpoint please:

https://developer.service.hmrc.gov.uk/api-documentation/docs/testing

Am I right in assuming the https://api-sandbox.tax.service.gov.uk/self-assessment/  endpoint won't do any authentication/authorisation/token validations?

**Comment by saurabharora80** [comment]
I am sorry but it's not as easy to change as it seems. 
Platform documentation is generated with standard specifications which apply to all HMRC API. 
The page you mentioned above lists the platforms standard _sandbox_ approach, which we found to be quite limited for our API so we decided to deviate from it.
The platform documentation pertaining to _sandbox_ would update at some point in the future when the new approach (i.e SA API's approach) has been standardised.

**Comment by osblue13** [comment]
@saurabharora80  thank you for the clarification. To my second question

> Am I right in assuming the https://api-sandbox.tax.service.gov.uk/self-assessment/ endpoint won't do any authentication/authorisation/token validations?

Are we to simulate this behaviour through the Gov-Test-Scenario headers for the sandbox env?

**Comment by P-Tracy** [comment]
@osblue13 Can I just ask why you assumed that?  Did you read that somewhere?  

We were told the new APIs would be hosted in an environment that reflected live, so would have the relevant authentication/authorisation implementation required.  Which I now don't think we have?

But also, the scenarios outlined in the Test Data section I'm looking at (GET on Obligations) doesn't list OAuth errors, they're more business relationship or data relationship errors that I would presume are beneath the OAuth flow.  i.e. you'd only check if the 64-8 relationship was in place if you passed the basic authentication/token validation check?

**Comment by osblue13** [comment]
@P-Tracy I believe I read the documentation wrong.

@saurabharora80 Can you answer the following please?

> Am I right in assuming the https://api-sandbox.tax.service.gov.uk/self-assessment/ endpoint won't do any authentication/authorisation/token validations?

If above is true, how are we meant to test this?

**Comment by saurabharora80** [comment]
@osblue13  The Sandbox environment hosted at  https://api-sandbox.tax.service.gov.uk/self-assessment/ **doesn't** do Authentication/Authorisation. 
It would soon be replaced with ETE (External Test Environment) which would perform Authentication/Authorisation.

**Comment by saurabharora80** [comment]
@osblue13 You can simulated 3 Authentication/Authorisation scenarios namely 

AGENT_NOT_SUBSCRIBED
AGENT_NOT_AUTHORIZED
CLIENT_NOT_SUBSCRIBED

using 'Gov-Test-Scenario' header.

**Comment by saurabharora80** [comment]
@osblue13 
`We were told the new APIs would be hosted in an environment that reflected live, so would have the relevant authentication/authorisation implementation required. Which I now don't think we have?`
The new testing environment (ETE), which is going LIVE soon, would provide this functionality.

**Comment by saurabharora80** [comment]
@osblue13 @P-Tracy are you happy for me to close this issue?

**Comment by P-Tracy** [comment]
I am!
