### ISSUE TITLE
bug with more than 3 scopes

### ISSUE THREAD

**Issue by forbescomputers** [hmrc/self-assessment-api#350]
If you try an oauth request with more than 3 scopes no error is raised, but only 3 are listed in the login UI and only those 3 are granted. For the SA prepop there are a total of 6 scopes meaning the user has to log on twice which is a bit pants.

**Comment by hughfdjackson** [comment]
Hi @forbescomputers 

We've heard this bug through a different source as well (although I don't know who the originator of that report was - perhaps yourself?).  We've been unable to replicate this, however.  

## Reproduction Steps

I went through the oauth authorization process for getting a sandbox token in Production. 

I requested 4 scopes (hello read:individual-benefits  read:individual-income read:individual-tax) using this URL: https://api.service.hmrc.gov.uk/oauth/authorize?client_id=REMOVED&response_type=code&scope=hello%20read:individual-benefits%20read:individual-income%20read:individual-tax&redirect_uri=http://localhost:8080

When I went through the oauth-authorize journey, I can see all scopes represented in the grant page:

<img width="1392" alt="screen shot 2017-02-16 at 17 27 12" src="https://cloud.githubusercontent.com/assets/545689/23627152/7f440a22-02a7-11e7-83d3-e150145f8e21.png">

After I granted authority, I requested an oauth token, and received this result:

```json
{
  "access_token": "REMOVED",
  "refresh_token": "REMOVED",
  "expires_in": 14400,
  "scope": "hello read:individual-benefits read:individual-income read:individual-tax",
  "token_type": "bearer"
}
```

As you can see, all of the scopes I requested are represented here.

## Further details from you

If you could let us know:

* The oauth/authorize url you're using (feel free to remove the clientId)
* Whether you're using your testing or production credentials
* What response are they seeing from the oauth/authorize endpoint

Then we will be able to look into your issue further. 

Thanks,

Hugh

**Comment by forbescomputers** [comment]
I have done some further investigating.

I copied and pasted the url we are generating into the address bar of the
browser and it was fine.

The way we were invoking the users default browser from our module testing
environment meant the URL was getting truncated outside our software to
windows MAX_PATH - 260 characters, which corresponds to the url for about 3
and a half scopes.

I  have also discovered the issue does not affect our software outside of
module testing as it invokes the browser in a different way.

You may want to consider raising an error if there is an unknown a scope
(or half a scope), but otherwise you can close.


Forbes Computer Systems Ltd
Registered in England 2829879

**Comment by hughfdjackson** [comment]
Hi @forbescomputers, 

Great to hear you got to the bottom of the mystery.  

While I agree that an error message would be nice in this situation, we've opted to ignore invalid scopes to allow for _not_ breaking clients requesting out-of-date scopes when an API is retired, and its scopes therefore invalid (and deleted from our database of valid scopes).

I'll make sure the relevant people have seen this thread, in case it informs a future design decision to make problems like the one you encountered easier to spot :)

**Comment by saurabharora80** [comment]
@forbescomputers may I close this issue if you are happy with the resolution provided by @hughfdjackson

**Comment by forbescomputers** [comment]
yes


Forbes Computer Systems Ltd
Registered in England 2829879
