### ISSUE TITLE
ETE Authentication?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#352]
Is the new test environment configured to do authentication?  

If not, when will it be?

**Comment by saurabharora80** [comment]
ETE would be configured to do proper Authentication and Authorisation, and to allow ease of testing we would provide a User Interface which would let you create test users/ninos.

**Comment by P-Tracy** [comment]
What do you mean 'would be'?  

Aren't the APIs pointing to ETE now?

**Comment by saurabharora80** [comment]
No. 

We have 2 environments right now. 

One is the LIVE/PROD hosted at _https://api.service.hmrc.gov.uk/self-assessment_ and which requires real/live NINOs and performs Authentication/Authorisation. 

The Other is Sandbox hosted at _https://api-sandbox.tax.service.gov.uk/self-assessment_ and which is IP restricted, can be used with any well formatted NINO and _doesn't_ performs Authentication/Authorisation. 

Going forward, the Sandbox would be replaced with new testing environment ETE.

**Comment by P-Tracy** [comment]
Ok. Sorry I may be being slow on the uptake but something isn't making sense. 

If I use the APIs now, are they stateful? Can I build up a narrative/workflow using a dummy NINO and self employment business? Where the data I supply is persisted and I can interact with it?

Or are the APIs still talking to the old test system that returned canned responses regardless of what data I supply?

We were informed that on 1st march we would have access to the full set of MVP APIs on a new stateful test environment and that here it would be as live like as possible, so reflect the authentication and authorisation functionality too. Are we not there yet?

**Comment by P-Tracy** [comment]
If these APIs are not taking to ETE, so are not stateful and cannot replicate live like behaviour including authentication and authorisation then the delivery date for when this is available is utterly critical for me. 

I cannot emphasise enough how important access to that is. We need that date.

**Comment by saurabharora80** [comment]
All APIs except for the calculations ones (Trigger and Retrieve) are **Stateful** in both environment listed above.

**Comment by P-Tracy** [comment]
OK - so when will sandbox have authentication in it?

**Comment by saurabharora80** [comment]
@P-Tracy  Sandbox would soon be release with ETE, which would have Authentication/Authorisation.

**Comment by saurabharora80** [comment]
@P-Tracy can I close this issue?

**Comment by P-Tracy** [comment]
sure
