### ISSUE TITLE
Prod = Sandbox?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#353]
Is the HMRC production environment reflective of Sandbox now?

**Comment by sudoku007** [comment]
Hi P-Tracy,

The only major difference is for Sandbox, OAUTH authentication process is disabled so you don't need to have OAUTH authentication to hit the endpoints on the Sandbox. However you would need OAUTH authentication to access production environment.

The production and sandbox environment both have the same behaviour (API). The API documentation is hosted on the production environment.

Regards,
Chandra
