### ISSUE TITLE
Numbers of calculations per 24 hrs

### ISSUE THREAD

**Issue by saurabharora80** [hmrc/self-assessment-api#354]
Given the following:

> To meet their obligations, taxpayers are required to submit regular financial updates for each of their businesses. Typically these updates cover four 3-month obligation periods, with one set of obligation periods per business per accounting period. To meet the taxpayer's obligation for a particular obligation period for a business:

> Supply summarised transactions for income and expenditure for the the whole of the obligation period for that specific business
Request a tax calculation

Would you please clarify whether triggering a first calculation in a 24 hour period will prevent a subsequent recalculation within the 24 hour period?

Raised on behalf of @andyws

**Comment by saurabharora80** [comment]
@andyws We will raise a question with TDG and get back to use shorty.

Internal Use
[MTDSA-971](https://jira.tools.tax.service.gov.uk/browse/MTDSA-971)

**Comment by andyws** [comment]
Thanks
