### ISSUE TITLE
How to simulate end of obligation period?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#355]
Is there any way for us to simulate the end of the obligation date range?  To trigger the code on your side to execute the 'met' logic?

**Comment by saurabharora80** [comment]
GET /self-assessment/ni/{nino}/uk-properties/obligations
GET /self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/obligations
with Gov-Test-Scenario= ALL_MET

Please see the Obligations resources in the documentation for details.

**Comment by P-Tracy** [comment]
Sorry, as usual I'm confused.

That would infer the code would be executing the logic to assess if all 4 obligations are met.  When we'd only have provided Update Periods for the first one.  Is that right?

So are you saying the code would then change the first met to true, and the remaining 3 would be false and I'd get errors back?

**Comment by saurabharora80** [comment]
The 'Gov-Test-Scenario' header lets you simulate canned response for certain edge case which are are hard achieve with real data. 
when you call

```
GET /self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/obligations
with Gov-Test-Scenario= ALL_MET

```

you would get a canned response with 4 Obligation periods which have all been met.

**Comment by P-Tracy** [comment]
OK.  So for self employments, there's no way we can simulate a live-like scenario for the obligation date range being met or exceeded?  

No way to change the date on the system to force that code to execute?

**Comment by GlassAndOneHalf** [comment]
We currently don't provide any kind of dynamic solution for the data returned by the obligation endpoints. You can use the headers we provide to simulate the various scenarios that are listed in the documentation, but nothing else at this time.

**Comment by P-Tracy** [comment]
Takes me a while to process these things.....  

If we can only simulate the execution of the 'met = true/false' logic via a header field that will by-pass the implementation and return me a canned response .... how do we test the positive and negative scenarios for meeting the obligation?

**Comment by P-Tracy** [comment]
@GlassAndOneHalf - sorry, I was typing as you replied.

The obligation dates will be dynamically generated based on the accounting periods of the fake self employments we create during test, no?

**Comment by GlassAndOneHalf** [comment]
@P-Tracy For UK properties, the dates returned by the obligations endpoint will be aligned to the accounting period, split into four quarters. However, for self-employments the obligation dates are currently aligned with the 2017-18 tax year as this is a restriction imposed by our MVP. This will most likely change at some point post-MVP as certain complexities are resolved.

**Comment by P-Tracy** [comment]
OK.  I'm not sure I was aware of that.

To come back to testing though, there's no ability to test this then?  The met logic?

**Comment by GlassAndOneHalf** [comment]
The met logic will be performed by another backend system - we are not implementing the logic behind meeting obligations ourselves, so we are providing these headers to allow you to simulate what this backend system might return to us (which we then send on to you).

However, if there are any scenarios you would like us to add to our header-based simulation, please do let us know and we will try to accommodate this.

**Comment by P-Tracy** [comment]
I think we would need as a bare minimum:

1. Simulate the end of obligation 1 date where the obligation changes to met
2. Simulate the end of obligation 1 date where the obligation does not change to met
(and repeat scenario 2 for every error scenario that can be thrown)

If I'm honest, I am looking to HMRC to tell me the scenarios I need to simulate; either via my interpretation of the positive and negative flows I interpret from the API, or where those are lacking via the scenarios you've already tested yourself

**Comment by saurabharora80** [comment]
@P-Tracy Right now we have simulated 3 scenarios for Obligations

Default: The First Period is met and Other 3 are not met
ALL_MET: All 4 Periods ar met
NONE_MET: None of the Periods are met

There are infact several combinations for Obligations, all of which would be too much to simulate. 
Please note that these are **not** failure for the Obligation resource; they are merely 3 of the several combinations of the happy case response. 

Each scenarios for each resource are listed separately along with each resource in the documentation.

**Comment by P-Tracy** [comment]
@saurabharora80 Thanks for that.

From your response, I guess what I am therefore asking is, when will the failure of the Obligation resource scenarios be supported?
