### ISSUE TITLE
Fully integrated test environment availability?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#356]
In an API world I can't help but feel I shouldn't know this ... but I now do.  In response to a previous query we were told:

"The met logic will be performed by another backend system - we are not implementing the logic behind meeting obligations ourselves, so we are providing these headers to allow you to simulate what this backend system might return to us (which we then send on to you)."

On what date will there be a test environment available for us to test against with all the moving parts for MVP integrated behind the scenes?

**Comment by saurabharora80** [comment]
@P-Tracy This ties into bigger question of API roadmap, which was also raised in #339.

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

We have an external testing environment which will be available for use by you before the end of this month.

Thanks,
Jacob

**Comment by P-Tracy** [comment]
Hi @GlassAndOneHalf 

Thanks.  

So in this environment, everything will be there?  Authentication, self assessment, obligations, subscriptions?  Everything will be integrated together?  

Also, will you let us know in advance when you'll do the change?  As I presume our tests may return different results when the change is made?

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

The new external testing environment will be the same as the current testing environment available to you, but authentication will now be enabled - we are not currently integrating with any other systems. I'll leave this issue open until we receive further info from the business about providing a fully integrated testing environment.

Your tests should function as before, providing that you are authenticated.

Thanks,
Jacob

**Comment by P-Tracy** [comment]
Ah ok.  I didn't know that.  

Can you make sure SDS tells us when this switch is scheduled to happen?  Currently we are taking advantage of the lack of authentication, so we need to make sure our testers know when this will no longer be possible.

Thanks
