### ISSUE TITLE
How many businesses in the GET List?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#357]
Given the HMRC subscription process is now open to everyone, including people who have multiple businesses - what will the 'get list' of businesses return?

Is it only the nominated business for MTD?  Or is it all businesses associated with that person?

Or for the period of time where MTD can only accommodate one self-employment, does it just return one but return more when the scope opens up?

We're trying to design the UI for the matching process at the moment and I don't know if I'll only ever get one back or if I'll get multiple from the outset

**Comment by saurabharora80** [comment]
@P-Tracy The MTD for people with either 1 Self-Employed Business and/or UK Properties Business. 

We would only return back the Self-Employed Business which the Customer provided while _Subscribing_ to MTD via the GET /self-assessment/ni/{nino}/self-employments 

So expect GET /self-assessment/ni/{nino}/self-employments to return a list of size **1** for MVP.

**Comment by P-Tracy** [comment]
Wonderful, thanks.  Feel free to close!
