### ISSUE TITLE
Sandbox environment SSL certificate has expired

### ISSUE THREAD

**Issue by osblue13** [hmrc/self-assessment-api#358]
Hi,

It looks like the ssl certificate for the sandbox environment (https://api-sandbox.tax.service.gov.uk/) has expired.  http://imgur.com/a/pXHhE

Can we get this fixed ASAP please. Its blocking our testing.

**Comment by dabd** [comment]
Hi osblue13,

The SSL has been renewed.  Apologies for the inconvenience caused.

Thank you.

**Comment by kaladin-storm** [comment]
Thank you.
