### ISSUE TITLE
Internal server on sandbox environment

### ISSUE THREAD

**Issue by osblue13** [hmrc/self-assessment-api#360]
I am doing a get request on https://api-sandbox.tax.service.gov.uk/self-assessment/ni/AB123456A/self-employments

But I am getting 500 error back. This used to work last week.

`{ "statusCode": 500, 
   "message": "(/_id/businessPostcode,List(ValidationError(List(error.path.missing),WrappedArray()))), (/_id/tradingName,List(ValidationError(List(error.path.missing),WrappedArray()))), (/_id/businessAddressLineOne,List(ValidationError(List(error.path.missing),WrappedArray()))), (/_id/businessDescription,List(ValidationError(List(error.path.missing),WrappedArray())))" }`

**Comment by rakeshavasarala** [comment]
Hi osblue13,

The issue is resolved. You should be able to access the end-points now.
The issue is being caused by the old data which should have been cleared down before the last deployment.

Sorry for the inconvenience.

Regards
Rakesh

**Comment by rakeshavasarala** [comment]
Hi osblue13,

I made a post request for the nino AB123456A, using the payload from the documentation 
(https://www.tax.service.gov.uk/api-documentation/docs/api/service/self-assessment-api/1.0#selfemployment-business_add-a-selfemployment-business-test-only_post_accordion).

So you might notice that data has changed. 
You can always update the values using the "Update a self-employment business [test only]"

Regards
Rakesh

**Comment by osblue13** [comment]
Cool thanks!
