### ISSUE TITLE
Paper versus API SA Return

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#363]
Hello

If an individual takes part in the Public Beta, in theory they do not have to complete a paper return.  But from what I have understood there are a lot of complexities and subtleties around when they will and will not have to also submit a 'paper' return.  

- Who determines this?  
- What are the rules around this?
- Is the scope or the rules expected to change/flex within public beta?
- Will HMRC notify the individual if they cross the boundary from API-only to API + Paper?  
- Or are the vendors expected to be able to work this out?

Thanks

**Comment by sudoku007** [comment]
Hi P-Tracy,

Business needs to answer these questions, so will forward it to them to answer these questions.

Regards,
Chandra

Internal Use
[MTDSA-980](https://jira.tools.tax.service.gov.uk/browse/MTDSA-980)

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

We have had a response from the business:

> There are circumstances where a customer will have to do both
> 
> - They choose not to declare personal income (or are unable to as using free software)
> - They have Income from Property and Self Employment and the Self Employment accounting period doesn’t match the tax year.

However, the business needs to define how these circumstances will be handled.

Thanks,
Jacob
