### ISSUE TITLE
Periods in the future?

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#364]
When I POST a new Self-Employment period, it is possible to create for dates in the future?  Or is there validation on the data to ensure the start and end are today or in the past?

**Comment by sudoku007** [comment]
Hi P-Tracy,

As of now there are no validations on the start/end dates to ensure that they are in the past.

However, this may change in the future as the business rules for period dates are currently in the process of being defined. When these are defined and implemented, we will amend our documentation to reflect the change.

Regards,
Chandra

**Comment by P-Tracy** [comment]
Any idea on dates for defining such things?  They're really core to our interpretation of the APIs and how we make best use of them.
