### ISSUE TITLE
nino validation

### ISSUE THREAD

**Issue by PreetiValand** [hmrc/self-assessment-api#369]
Hi, 

I'm testing Nino, using lower case nino displays a message: Nino is invalid. It seems like AB123456C works, however AB123456c does not work. 

Status: 400 Bad Request
Details: 
[
  {
    "type": "HMRC_EXCEPTION",
    "code": "NINO_INVALID",
    "description": "The provided Nino is invalid",
    "location": ""
  }
]
Would you look to correct this?

**Comment by GlassAndOneHalf** [comment]
Hi @PreetiValand 

At the moment, the validation we perform expects all NINOs to be upper case. It is unlikely we will  be able to change this in the near future, but I will add your comments to our backlog for review at a later date.

Thanks,
Jacob

**Comment by PreetiValand** [comment]
Thanks
