### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by NickyJP** [hmrc/self-assessment-api#370]
We're just beginning to test calls to the MTD API, so beginning at the top with the List all self-employed businesses: /self-assessment/ni/{nino}/self-employments

Using Sandbox as base URL: https://api-sandbox.tax.service.gov.uk/

Full URL: https://api-sandbox.tax.service.gov.uk/self-assessment/ni/JC346091A/self-employments

Headers:

Accept:      application/vnd.hmrc.1.0+json
Content-Type: application/json
Bearer: ***********  (though optional for Sandbox I read)

Error Response:

'{
  "code": "INVALID_REQUEST",
  "message": "Invalid request",
  "errors": [
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/commencementDate"
    },
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/businessDescription"
    },
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/businessAddressLineOne"
    },
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/businessPostcode"
    },
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/tradingName"
    },
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/accountingType"
    },
    {
      "code": "MANDATORY_FIELD_MISSING",
      "message": "a mandatory field is missing",
      "path": "/accountingPeriod"
    }
  ]
}

Please advise ??

BR

**Comment by rakeshavasarala** [comment]
Hi,

Can you please confirm you are doing a HTTP GET call ?

The error message you mentioned is returned for a HTTP POST call.

Regards
Rakesh

**Comment by NickyJP** [comment]
Hi,

Sorry our bad.

Result returned though empty.  Are there are example NINOs to use that shall return data ?

Regards

**Comment by rakeshavasarala** [comment]
Hi,

You can setup your own test data by using the "Add a self-employment business [test only]" end-point. The documentation at https://www.tax.service.gov.uk/api-documentation/docs/api#self-assessment-api includes the sample payload.

You can use any valid NINO.

Regards
Rakesh
