### ISSUE TITLE
cessationDate issue

### ISSUE THREAD

**Issue by PreetiValand** [hmrc/self-assessment-api#374]
Hi,

What would be the best way to get the cessationDate to be populated? I have carried out the below and the value returns as null on our api's.

1. POST directly using /self-assessment/ni/{nino}/self-employments (Add a self-employment business [test only]) 
2. PUT direclty using /self-assessment/ni/{nino}/self-employments/{selfEmploymentId} (Update a self-employment business [test only])

Both do not return any values when doing a GET directly on HMRC. Happy to supply various nino's used during tests

**Comment by GlassAndOneHalf** [comment]
Unfortunately it is not currently possible to populate the cessationDate field, and as a result you will never be able to retrieve it using the GET endpoint. 

When the POST and PUT APIs are eventually changed to allow this, you will be able to retrieve it.

**Comment by PreetiValand** [comment]
Thanks for clarifying

On another note, If i supplied the SE ID during POST, it isnt being returned back, another one is assigned to it and returned during GET. Is that expected behaviour?

**Comment by GlassAndOneHalf** [comment]
You can't supply a self-employment ID when POSTing to create a new self-employment. When you perform a POST and receive a response, you will be able to see the self-employment ID in the "Location" header. E.g.:

`POST /ni/A999999AA/self-employments` will return a header `Location: <id>` if the creation is successful.

**Comment by PreetiValand** [comment]
Great, thanks.
