### ISSUE TITLE
SIC codes validation

### ISSUE THREAD

**Issue by PreetiValand** [hmrc/self-assessment-api#377]
Hi,

Whenever I change the businessDescription (on any of the POST/PUT API's), it displays a message 
 "business description must be a string that conforms to the UK SIC 2007 classifications".

I've looked at http://resources.companieshouse.gov.uk/sic/ and picked codes/ description from there, but that doesnt seem to work. Has this field been locked down to just serve "Accountancy services"?

**Comment by GlassAndOneHalf** [comment]
Hi @PreetiValand 

You need to use the business descriptions on that list. You can look at this file for reference: https://github.com/hmrc/self-assessment-api/blob/master/conf/SICs.txt

Note they must be exactly the same as in this file otherwise they will be rejected.

**Comment by PreetiValand** [comment]
Thanks @GlassAndOneHalf 

I've tested a handful from the list you supplied and that seems to have worked, however picking from my original link didn't. i.e. a couple not on the list you supplied are as below:
- Gathering of wild growing non-wood products
- Growing of rice

**Comment by GlassAndOneHalf** [comment]
Hi @PreetiValand 

We sourced our list from https://www.gov.uk/government/publications/standard-industrial-classification-of-economic-activities-sic so please use that for reference. It is likely that this requirement will be changed in the future to a free text field or similar, however, we are awaiting clarification from the business before we make any changes.

Thanks!

**Comment by PreetiValand** [comment]
Thanks @GlassAndOneHalf,

The list on the like you sent above has the information i was looking for, but your deployed version doesnt. There are discrepencies. 

Could you let me know when the field details are going to be changed to allow free text. We would have to allow for that.

**Comment by GlassAndOneHalf** [comment]
Hi @PreetiValand 

Unfortunately I can not give you a date at this time.

I have had another look at the SICs and it seems you are using the condensed list of SIC codes. Please use the "Main column" which can be found [here](https://www.ons.gov.uk/methodology/classificationsandstandards/ukstandardindustrialclassificationofeconomicactivities/uksic2007).
