### ISSUE TITLE
Obligation set to true for the first period

### ISSUE THREAD

**Issue by PreetiValand** [hmrc/self-assessment-api#378]
Hi,

I understand that the obligations are to be set to true when the information has been submitted. When I retrieve obligations for a newly createad SE, the first obligation seems to be set to true. Can this be corrected? 

{
  "obligations": [
    {
      "start": "2017-04-06",
      "end": "2017-07-05",
      "met": true
    },
    {
      "start": "2017-07-06",
      "end": "2017-10-05",
      "met": false
    },
    {
      "start": "2017-10-06",
      "end": "2018-01-05",
      "met": false
    },
    {
      "start": "2018-01-06",
      "end": "2018-04-05",
      "met": false
    }
  ]
}

**Comment by GlassAndOneHalf** [comment]
Hi @PreetiValand 

Obligations are currently test-only so you are receiving a pre-defined response. You can change this response by using the `Gov-Test-Scenario` header. More details about the responses you can receive can be found in the documentation on the [API Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation), provided you are in the private beta. 

Thanks!

**Comment by P-Tracy** [comment]
@GlassAndOneHalf You don't mean [test only] as in it's not going live on Monday?  

You mean it's test only in terms of the code not being executable on the existing test environment - which will be remedied when we get the new environment on Friday or Monday?

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

Apologies for the confusion, by "test only" I mean that the responses are canned. This endpoint will be available as part of MVP.

However, for the new environment they will continue to be canned until we receive further information from our downstream systems.

Thanks!

**Comment by P-Tracy** [comment]
@GlassAndOneHalf Thanks for that.

So, just to clarify, we will be going live having only been able to test 4 obligation scenarios, all canned.  When this API is activated on live (by HMRC), the vendors will be accessing this live API and executing that code base for the first time.

So obligations code will go through its first set of tests by vendors in live.
