### ISSUE TITLE
PeriodID and Updating Periods

### ISSUE THREAD

**Issue by NickyJP** [hmrc/self-assessment-api#379]
Am curious to workflow for MTD particularly around creation and updating of periods.

We see can update a period using:  Update a self-employment update period [test only], method: PUT

Path parameters: nino, selfEmploymentId, periodId

We understand the PeriodID is returned from create a period but what if the flow is not continuous and a user returns to update a period at a later date, how is the PeriodID obtained?  The get periods end point returns dates for given PeriodID so not useable.  Is there an expectation that once a period is created that the PeriodID is stored our side ??

Welcome advice around this.
Kind regards

**Comment by GlassAndOneHalf** [comment]
Hi @NickyJP 

You can use the retrieve all periods endpoint  (e.g. `/self-employments/{id}/periods`). This will return a list of summarised periods for a self-employment, each containing the from/to dates and its associated ID.

Thanks!

**Comment by NickyJP** [comment]
Thank you @GlassAndOneHalf, we missed that end point.
