### ISSUE TITLE
Authentication does not work on new test environment.

### ISSUE THREAD

**Issue by brvaland** [hmrc/self-assessment-api#384]
Hi,

I am getting an error "Bad Request - Please check that you have entered the correct web address." instead of granting the authority.

auth: https://test-api.service.hmrc.gov.uk/oauth/authorize
grant: https://test-api.service.hmrc.gov.uk/oauth/token

**Comment by dabd** [comment]
Hi brvaland,

Could you please provide the entire request data you are sending as well as if you are using 'curl' or other tool?

Thank you,
Dario

**Comment by brvaland** [comment]
Hi Dario

I have not changed anything since it was working fine with production URL expect the new endpoint. I am actually using https://adodson.com/hello.js/ for OAuth2.

**Comment by petrna** [comment]
Hi Dario

The error message has changed to "Bad CSRF token found in query String".

This token is present among the post parameters once I enter username and password on https://test-www.tax.service.gov.uk/api-test-login/sign-in and is not something I am required to supply.

Documentation does not mention this so I'm inclined to believe it is not my request that is incorrect.

**Comment by dabd** [comment]
Hi petrna,

Unfortunately this is still an unresolved issue in the API platform, apparently due to cookies when having multiple sessions open or when trying the same test call repeatedly.
Could you please try Incognito mode or clearing cookies?

Thank you,
Dario
