### ISSUE TITLE
Tax Agent functionality

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#387]
Is there any Tax Agent functionality available in the new sandbox?

**Comment by GlassAndOneHalf** [comment]
Hi @andyws 

At the moment, you are able to simulate Tax Agent authorisation and subscription check failures using the `Gov-Test-Scenario` headers `AGENT_NOT_AUTHORIZED` and `AGENT_NOT_SUBSCRIBED`.

We do not currently implement any other agents functionality.

Thanks,
Jacob

**Comment by andyws** [comment]
Hi @GlassAndOneHalf,  I'm curious because I've been following the 3/4 Agent projects on Github (where no question is ever answered), attended presentations to Agents and received a recent presentation from SDS.  It would appear that somewhere someone has access to some Agency functionality ... I wonder where?
