### ISSUE TITLE
POST - Period isn't working

### ISSUE THREAD

**Issue by saqibmushtaq** [hmrc/self-assessment-api#391]
Re: Endpoint    https://test-api.service.hmrc.gov.uk/self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/periods

Calling above endpoint for a newly created account which doesn't have any period created at all throws the error: "Periods should be contiguous and have no gaps between one another."

**Comment by P-Tracy** [comment]
Hello

Can I just ask for this to be responded to?  

Is this supposed to be active/working on the test environment?  Or is this endpoint supposed to be returning a 500 at the moment?

Thanks

**Comment by GlassAndOneHalf** [comment]
Hi @saqibmushtaq

When a period is created for the first time, the start date of that period should be the same as the start date of the accounting period, otherwise the period creation will fail.

@P-Tracy Can you provide more details of the 500 error you are receiving?

Thanks,
Jacob

**Comment by P-Tracy** [comment]
@GlassAndOneHalf Thanks for that.  

I wasn't getting a 500 - I just thought if the POST wasn't meant to be active then it should be returning a 500 instead of what we were getting.

Does this response imply that the obligation code has been merged onto this environment now?  As it's checking that the periods fall within the obligation date ranges?

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

The obligation code hasn't been merged. The period dates are checked against the accounting period dates, not the obligation dates.

If the period dates are incorrect, you should receive either a 400 or 409 error and not a 500. Could you please provide the response you are receiving? There may be a problem with our systems.

Thanks,
Jacob

**Comment by alibabas** [comment]
Hi @GlassAndOneHalf,
I have tried period with endpoint  https://test-api.service.hmrc.gov.uk/self-assessment/ni/SY343480A/self-employments/58fda3313100006401ec46de/periods
 but throw error:
{
  "code": "MATCHING_RESOURCE_NOT_FOUND",
  "message": "A resource with the name in the request can not be found in the API"
}

**Comment by GlassAndOneHalf** [comment]
Hi @alibabas 

You should have received an e-mail from SDST about this, though for anyone else reading, this issue is currently under investigation. I will update this ticket once we receive further information.

Thanks!

**Comment by alibabas** [comment]
Thanks GlassAndOneHalf :)

**Comment by P-Tracy** [comment]
@GlassAndOneHalf Is there any update on this?  We're not receiving any emails from SDS at the moment, so just wanted to see if this has been resolved as we aren't able to test without it

Many thanks

**Comment by GlassAndOneHalf** [comment]
Hi @P-Tracy 

Unfortunately we haven't yet received an update from team responsible. We are currently chasing this up with them. I will let you know when we get a response.

Thanks!

**Comment by alibabas** [comment]
Hi @GlassAndOneHalf,

I have received an e-mail from SDST about closure of the Integration Testing Environment on 31 May 2017. Do you have any update on the issue that i posted ?

Thanks!

**Comment by rakeshavasarala** [comment]
Hi @alibabas 

Apologies that it is blocking your testing and it has been escalated to concerned Platform and Gateway teams for resolution. Will update you as soon as we have a fix in place.

The following _Create Period_ end-points are still not working in the test Sandbox environment
POST /self-assessment/ni/{nino}/self-employment/{selfEmploymentId}/periods
POST /self-assessment/ni/{nino}/uk-properties/furnished-holiday-lettings/periods

Only _Create Period_ end-point working in the test Sandbox environment is 
POST /self-assessment/ni/{nino}/uk-properties/other/periods

**Comment by rakeshavasarala** [comment]
@alibabas 
The issue with self-employment period has been fixed in Sandbox environment.

**Comment by alibabas** [comment]
Hi @GlassAndOneHalf,
Because i cannot create a self-employment period so I have tried to create a self-employment business with endpoint https://test-api.service.hmrc.gov.uk/self-assessment/ni/PZ601664C/self-employments 
and i received an error 403
{
  "code": "CLIENT_NOT_SUBSCRIBED",
  "message": "The client is not subscribed to MTD",
  "path": ""
}

although Self Assessment (MTD) subscribed please refer this link https://ibb.co/jQgDRQ 

Thanks,

**Comment by rakeshavasarala** [comment]
@alibabas 

The image link that you mentioned is for your **APP** subscribing to MTD Self Assessment API on API Developer Hub.
The error from the API is for client (taxpayer) not subscribed to MTD. Client in this instance is user who is using the APP, i.e business.

You should have received 2 emails from SDST regarding Improved Authorisation on HMRC Developer Sandbox, which explains how to create test users.

You mentioned about an email from SDST about closure of Integration Testing Environment, the email should also have a section for **Improved Authorisation on HMRC Developer Sandbox**. If you have any queries regarding creation of Test Users, please contact the SDST.
