### ISSUE TITLE
GET with a new NINO displays 200 instead of 204

### ISSUE THREAD

**Issue by PreetiValand** [hmrc/self-assessment-api#392]
When I do a GET on All SE for a newly created NINO(through the api-test-user), the status is 200 ok, instead of 204 : No content. 

Is that intended behaviour?

**Comment by GlassAndOneHalf** [comment]
Retrieving all self-employments will always return 200 containing an empty array if there are no self-employment sources.

**Comment by PreetiValand** [comment]
Thanks
