### ISSUE TITLE
Redirect URI is being set to https://www-externaltest.tax.service.gov.uk

### ISSUE THREAD

**Issue by GitHubMan12** [hmrc/self-assessment-api#440]
Previously it was using the redirect URI that we provided in the Redirect URI field on our developer sandbox profile. This has now changed to https://www-externaltest.tax.service.gov.uk

**Comment by IainWardle** [comment]
We're experiencing the same issue, please can someone look at this as a matter of urgency as it's currently a blocker.

**Comment by dabd** [comment]
Hi @GitHubMan12 @IainWardle This issue is currently being investigated by the API Platform team.  We will notify as soon as it is resolved.  Thank you.

**Comment by Donoss** [comment]
API Services are investigating this issue.....

**Comment by Wavemachine007** [comment]
Is there any progress on this as it has been blocking us since last Wednesday morning (31/5/2017 which we reported then)!

**Comment by dabd** [comment]
Hi @Wavemachine007 unfortunately this seems to be an intermittent issue.  It has been prioritised as urgent and the Platform support is working on it.  We will provide an update as soon as possible.

**Comment by dabd** [comment]
The issue has been resolved.  Can you please test and confirm?  Thanks.

**Comment by Wavemachine007** [comment]
Seems to be working now thanks.
