### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#441]
Just received the below email.  Can you clarify what has been released and to which environment?  What Github tag does this release relate to?

> Dear Developer,
> 
> We’re pleased to confirm that we have now successfully released a number of APIs which enable those businesses and landlords who have subscribed to MTD Income & Expenses to use their software to send us a summary update. Similarly, agents who have subscribed to Agent Services can also send us a summary update on behalf of their client, provided the client is subscribed to MTD and an agent/client relationship is established in the Agent Services account.
> 
> The following endpoints have now been released:
> •            List all self employment businesses
> •            Get a self employment business
> •            Create a self employment update period
> •            Update a self employment annual summary
> •            Get a UK property business
> •            Trigger a tax calculation
> •            Retrieve a tax calculation
> •            Retrieve self employment business obligations 
> •            Retrieve all UK property obligations 
> 
> We now expect to release the following further endpoints mid-June:
> •            Create a non FHL property update period
> •            Update a non FHL property business annual summary 
> •            Create a FHL property update period 
> •            Update a FHL UK property business annual summary 
>  
> 
> Agent Services
> 
> We have now released a feature that allows agents to add existing self assessment clients to their new Agent Services account, without the need for agents to re-authorise these clients
> 
>

**Comment by rakeshavasarala** [comment]
0.117.3 deployed Production and Sandbox

**Comment by nealpastel** [comment]
Hi 

We have not received this email could you please re-send?

Thanks

**Comment by rakeshavasarala** [comment]
@nealpastel The email was sent by Software Developers Support Team to the Beta developers.  They manage all the comms and support for 3rd party developers. Could you please email SDSTeam@hmrc.gsi.gov.uk regarding the comms.
