### ISSUE TITLE
Running API locally

### ISSUE THREAD

**Issue by dharma66** [hmrc/self-assessment-api#446]
Is it possible for us to run this project (self-assessment-api) locally?
I've tried following instructions, but it seems to require saervicemenager, which in turn seems to require NEXUS credentials, which I assume is an internal tool?

If there's a way for us to run something locally that would be great, as it would remove the need for us to create a stubbed version of your APIs to permit load and performance testing.

**Comment by GlassAndOneHalf** [comment]
Hi @dharma66 

Apologies for the delay in getting back to you. Unfortunately it will not be possible for you to run this project locally as it depends on some internal libraries that are not public.

Thanks,
Jacob
