### ISSUE TITLE
"code": "CLIENT_NOT_SUBSCRIBED"

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/self-assessment-api#447]
I have created an MTD user using the create user API and here is the user:
{"userId":"204966079022","password":"9oh3epSlms1s","saUtr":"6000062443","nino":"SG774123B","mtdItId":"XBIT00000652298"}
With user name and password above I obtain an authorization code for self assessment scopes: "write:self-assessment read:self-assessment" which is displayed correctly when granting the application permission. I then exchange the code for a token.
This business data is literally like this:
{
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
  "accountingType": "CASH",
  "commencementDate": "2016-01-01",
  "tradingName": "Acme Ltd.",
  "businessDescription": "Accountancy services",
  "businessAddressLineOne": "1 Acme Rd.",
  "businessAddressLineTwo": "London",
  "businessAddressLineThree": "Greater London",
  "businessAddressLineFour": "United Kingdom",
  "businessPostcode": "A9 9AA"
}

Then I do a POST to this endpoint:  "self-assessment/ni/SG774123B/self-employments" to create / Add a self-assessment business and here is what comes back:
{
  "code": "CLIENT_NOT_SUBSCRIBED",
  "message": "The client is not subscribed to MTD"
}
The idea is to create a self assessment / self employment business without which one cannot POST a self assessment income / expenditure transaction.

What am I missing? Can someone please shed some light?

**Comment by rakeshavasarala** [comment]
Hi,
The steps you have described above are correct and POST should have been successful. 
We are investigating.

**Comment by rakeshavasarala** [comment]
Hi,

Could you please use _**Create a test user which is an organisation**_ (/create-test-user/organisations) end-point instead of _**Create a test user which is an individual**_ (/create-test-user/individuals) for creating Test user. 

This is should fix the issue.

Regards
Rakesh

**Comment by mathiasbanda** [comment]
Yes that works brilliantly. Thanks Rakesh

**Comment by mathiasbanda** [comment]
I just assumed it was still work in progress and switched to organization instead
