### ISSUE TITLE
/self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/periods/{periodId}

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/self-assessment-api#454]
{
  "code": "TAX_YEAR_INVALID",
  "message": "Tax year invalid"
}

I created a self ass period update with a sample data:
{
  "from": "2017-04-06",
  "to": "2017-07-04",
  "incomes": {
    "turnover": { "amount": 100.25 },
    "other": { "amount": 100.25 }
  },
  "expenses": {
    "costOfGoodsBought": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "cisPaymentsToSubcontractors": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "staffCosts": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "travelCosts": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "premisesRunningCosts": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "maintenanceCosts": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "adminCosts": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "advertisingCosts": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "interest": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "financialCharges": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "badDebt": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "professionalFees": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    },
    "depreciation": {
      "amount": 100.25,
      "disallowableAmount": 100.25
    },
    "other": {
      "amount": 100.25,
      "disallowableAmount": 50.25
    }
  }
}
and it works. Now I have the id I am trying to update (PUT) the record and it comes with error 400:

{
  "code": "TAX_YEAR_INVALID",
  "message": "Tax year invalid"
}
I am using the sample data. so what / which tax year is invalid?

**Comment by GlassAndOneHalf** [comment]
Hi @mathiasbanda 

Could you provide the full URL you are attempting to PUT to?

**Comment by mathiasbanda** [comment]
it this: /self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/periods/{periodId} which in my case translates to:
https://test-api.service.hmrc.gov.uk/self-assessment/ni/BK321330B/self-employments/5947c38b2f00003a00ccfbd1/periods/2017-04-06_2017-07-04

**Comment by rakeshavasarala** [comment]
Hi mathiasbanda

From the logs, i can see that the URL for PUT is missing a "/" after periods.

This is the url from our logs:
`/self-assessment/ni/BK321330B/self-employments/5947c38b2f00003a00ccfbd1/periods2017-04-06_2017-07-04`

The GET calls have the correct URL and they are returning correct data.


Regards
Rakesh

**Comment by mathiasbanda** [comment]
Rakesh,

You're absolutely right. Sincere apologies for time wasting. SORRY

KR

Mathias

**Comment by mathiasbanda** [comment]
no longer an issue
