### ISSUE TITLE
Will an agent have to go through multiple Oauth handshake for each of his/her client ?

### ISSUE THREAD

**Issue by sri-akshat** [hmrc/self-assessment-api#479]
Let's say an Agent (Accountant) has 10 clients. Will he have to go through 10 Oauth flows and get 10  access tokens, one for each client ?
Or there will be Oauth once and the same access token will suffice for accessing data of all 10 clients.

**Comment by dabd** [comment]
Hi sri-akshat, the same OAuth token can be used for all clients as long as the Agent-Client relationships are in place.

**Comment by sri-akshat** [comment]
Thanks @dabd

**Comment by dabd** [comment]
Hi sri-akshat,
A correction to the previous answer: if the agent is using the client's credentials, then he will have to go through multiple OAuth flows and get multiple access tokens, one for each client.
If the agent is using his own credentials, the same access token can be used for all clients.
