### ISSUE TITLE
VAT

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#511]
Hi guys,

I understand that the VAT APIs will be ready sometime soon. It'd be great to see them, even in draft format, so we can see how they differ from submitting via the Transaction Engine.

I have a specific question around subscription. MTD ITSA subscription makes a lot of sense for ITSA, but perhaps less sense (as it stands) for VAT. Will there be a VAT subscription process please?

Thank you,

Alex

**Comment by rakeshavasarala** [comment]
Alex,

Work on VAT API's might start in next sprint. I will let you know once the project is on github for you to have a look at the public facing contracts.

VAT subscription process - Most likely there will not be a separate VAT subscription but I will confirm with business and come back to you.

Regards
Rakesh

**Comment by alexec** [comment]
Thank you very much!

**Comment by rakeshavasarala** [comment]
@alexec 
Users will need to subscribe to MTD-VAT. 

We have created a vat-api github repo. You can direct any MTD VAT API related questions to that repo.

Please note that github issues should only be raised for Technical questions/issues. Business or Delivery related questions should be re-directed to SDST.

**Comment by alexec** [comment]
Thank you.
