### ISSUE TITLE
Add a Self Employment business 400 error since 5/10/2017 update

### ISSUE THREAD

**Issue by Wavemachine007** [hmrc/self-assessment-api#521]
The specification for the JSON schema seems to have changed when adding a self-employment business in the sandbox looking at the documentation.

Our existing code now fails with a 400 error:

{"error":{"code":400,"message":"A mandatory value has not been provided","errors":[{"message":"A mandatory value has not been provided","location":"/description"},{"message":"A mandatory value has not been provided","location":"/address"}]}}

Even if we use the new schema and the example you have given i.e:

{
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
  "accountingType": "CASH",
  "commencementDate": "2016-01-01",
  "tradingName": "Acme Ltd.",
  "description": "Accountancy services",
  "address": {
    "lineOne": "1 Acme Rd.",
    "lineTwo": "London",
    "lineThree": "Greater London",
    "lineFour": "United Kingdom",
    "postalCode": "A9 9AA",
    "countryCode": "GB"
  }
}

We get the same error.

This started happening after the 5th October update and we are now in a position where our code is broken and we can't currently run our MTD tests.

Surely if you are going to be changing schemas then you should apply versioning, also looking at the release notes there is no mention of the create self-employment having changed only the update periods in that area.

We would be grateful if you could investigate this as a matter of urgency and even consider rolling back as this is having a massive impact on our development for MTD pilot users.

**Comment by hicnar** [comment]
Thank you for pointing that out. We're investigating that issue!

**Comment by Wavemachine007** [comment]
We have tested it again with some different data and it does appear to work if we pass in the new formatted data.

However this breaking change was not documented and should have used a versioned end point. We would have to effectively support two schemas for the MTD pilot, one for test and one for live.

Given this is a breaking change which we were not warned about or given sufficient time to respond to it we would suggest that the old schema is reinstated ASAP and if you must change the schema then you need to version your end points.

To quote from the documentation: 

https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/1.0

"Versioning

Specific versions are requested by providing an Accept header. When backwards-incompatible API changes are made, a new version will be released. Backwards-compatible changes are released in the current version without the need to change your Accept header. See our reference guide for more on versioning."

**Comment by andyws** [comment]
@Wavemachine007  which specific schema are you referring to?

**Comment by Wavemachine007** [comment]
The schemas for a self employment business:

Add a self employment business:

Request
{
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
  "accountingType": "CASH",
  "commencementDate": "2016-01-01",
  "tradingName": "Acme Ltd.",
  "description": "Accountancy services",    <-- Previously business description
  "address": {                                              <-- Previously not there 
    "lineOne": "1 Acme Rd.",                       <-- Previously businessAddressLineOne
    "lineTwo": "London",                             <-- Previously businessAddressLineTwo
    "lineThree": "Greater London",             <-- Previously businessAddressLineThree
    "lineFour": "United Kingdom",             <-- Previously businessAddressLineFour
    "postalCode": "A9 9AA",                      <-- Previously businessPostcode
    "countryCode": "GB"                            <-- New
  }
}
Get a self employment business

{
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
  "accountingType": "CASH",
  "commencementDate": "2016-01-01",
  "cessationDate": "2018-04-05",
  "cessationReason": "005",
  "tradingName": "Acme Ltd.",
  "description": "Accountancy services",    <-- Previously business description
  "address": {                                              <-- Previously not there 
    "lineOne": "1 Acme Rd.",                       <-- Previously businessAddressLineOne
    "lineTwo": "London",                             <-- Previously businessAddressLineTwo
    "lineThree": "Greater London",             <-- Previously businessAddressLineThree
    "lineFour": "United Kingdom",             <-- Previously businessAddressLineFour
    "postalCode": "A9 9AA",                      <-- Previously businessPostcode
    "countryCode": "GB"                            <-- New
  },
  "contactDetails": {
    "primaryPhoneNumber": "07712345678",
    "secondaryPhoneNumber": "07712345678",
    "faxNumber": "07712345678",
    "emailAddress": "admin@acmeltd.com"
  },
  "paperless": false,
  "seasonal": false
}

List self employment businesses also affected

Not sure if other schemas have changed as we haven't got that far running our tests, please not this was all working fine until 5/11/2017 update!

**Comment by andyws** [comment]
As I understand it we currently are working with 0.136.2.  @HMRC Is this correct?

The RAML + 4 json schemas concerned are SelfEmployment*.json.  The ALL show:

businessAddressLineXXX:
...
businessPostcode:

In only 2 out of 4 "businessAddressLineOne and businessPostcode is required.

@HMRC: Factoring out "Address" into a distinct type makes sense but where is this documented in the RAML?

@HMRC: What are the versions/tags of the SA codebase in github which relate a) to the Sandbox and b) to Live?

**Comment by andyws** [comment]
Hello HMRC could you acknowledge/answer my questions.  

It has been a working day since I posted my request both here and to SDS and I have not heard a thing.

**Comment by andyws** [comment]
Just received a message from SDS which included an email sent last week which I do not appear to have received which states that the version in the sandbox is 0.138.0.  **I presume the version in live is 0.136.2?**

I think it is a reasonable and practical question to get a more detailed report of changes and have a discussion of what constitutes a breaking change.  For instance the following report of differences between live and sandbox at least gives a clue to where to look for changes:


Left Orphan Files (5) | Size | Modified
-- | -- | --
schemas\self-employment\Class4ExemptionCode.json | 588 | 13/10/2017 11:40:27
schemas\self-employment\NonFinancials.json | 1,151 | 13/10/2017 11:40:27
schemas\Address.json | 1,866 | 13/10/2017 11:40:27
schemas\CessationReason.json | 645 | 13/10/2017 11:40:27
schemas\ContactDetails.json | 1,309 | 13/10/2017 11:40:27
Right Orphan Files (0) | Size | Modified
Left Newer Files (0) | Size | Modified
Right Newer Files (0) | Size | Modified
Differences Files (8) | Size | Modified
schemas\SE_AnnualSummary.json | 413 | 13/10/2017 11:40:27
  | 329 | 11/10/2017 23:26:25
schemas\SE_Period_Without_ID.json | 1,066 | 13/10/2017 11:40:27
  | 617 | 11/10/2017 23:26:25
schemas\SE_UpdatePeriod.json | 800 | 13/10/2017 11:40:27
  | 351 | 11/10/2017 23:26:25
schemas\SelfEmployment.json | 1,568 | 13/10/2017 11:40:27
  | 2,666 | 11/10/2017 23:26:25
schemas\SelfEmployment_Create_Without_ID.json | 1,335 | 13/10/2017 11:40:27
  | 2,481 | 11/10/2017 23:26:25
schemas\SelfEmployment_Update.json | 2,117 | 13/10/2017 11:40:27
  | 1,853 | 11/10/2017 23:26:25
schemas\SelfEmployment_Without_ID.json | 2,038 | 13/10/2017 11:40:27
  | 2,627 | 11/10/2017 23:26:25
application.raml | 68,670 | 13/10/2017 11:40:27
  | 66,847 | 11/10/2017 23:26:25

**Comment by sudoku007** [comment]
@Wavemachine007 We are working on reverting the Address changes which caused the backward compatibility to break with the API's.

@andyws The breaking changes have been introduced in the pre release version `0.138.0`, its only in the sandbox and has not been promoted to production yet. What you mentioned in terms of the changes are right. We created a new Address node, but it caused the backward compatibility to break.

 We are hoping to release a version early next week which should revert these changes.

**Comment by sudoku007** [comment]
@andyws Yes the production release version is still `0.136.2`

**Comment by Wavemachine007** [comment]
@sudoku007 Many thanks, I assume you will also be rolling back the description to businessDescription also?

**Comment by sudoku007** [comment]
@Wavemachine007 Yes we will rollback `description to businessDescription also?` and all other  changes which caused the backward compatibility to break.

**Comment by andyws** [comment]
@sudoku007 Do you mean to roll back to 0.136.2?

**Comment by andyws** [comment]
Given that factoring out Address is clearly sensible and an improvement over what preceded it can I ask what your strategy is for managing change?  There is a great danger that we will end up with a less than optimal set of interfaces if you are unable to make sensible improvements.
