### ISSUE TITLE
Getting the customer's NINO.

### ISSUE THREAD

**Issue by alexec** [hmrc/self-assessment-api#530]
Hi everyone, 

So that we can have more successful sign-ups, we would like to pre-populate the customer's NINO in QuickBooks' user interface.

Once a customer has completed the OAuth flow, I don't believe there is currently a way to get their NINO. Can I ask if there's a way to raise a change request or this feature?

Thank you,

Alex

**Comment by dabd** [comment]
Hi Alex,

Apologies for the late reply.  Can you please raise this issue through SDST SDSTeam@hmrc.gsi.gov.uk?  This issue is beyond the scope of our API and they might be able to address it.

Thanks,
Dario

**Comment by alexec** [comment]
Thank you!
