### ISSUE TITLE
Returning CLIENT_NOT_SUBSCRIBED instead of NINO_INVALID for incorrect NINO

### ISSUE THREAD

**Issue by DBrown2207** [hmrc/self-assessment-api#541]
The sandbox environment is returning CLIENT_NOT_SUBSCRIBED instead of NINO_INVALID when using the endpoints (eg. /self-assessment/ni/{nino}/self-employments) in the case where the NINO is syntactically valid but does not match with the authorised user.

Correct NINO:
![image](https://user-images.githubusercontent.com/12028563/33265043-fa9184e8-d367-11e7-9982-04ddeb88a7cc.png)
Incorrect NINO:
![image](https://user-images.githubusercontent.com/12028563/33265072-19de4520-d368-11e7-9320-3fa22bba3ab9.png)
Badly formatted NINO:
![image](https://user-images.githubusercontent.com/12028563/33265091-2ecb5fe0-d368-11e7-9825-dbc07df1d83d.png)

Steps to reproduce:
1. create organisation user
2. perform oauth with organisation user
3. call /self-assessment/ni/{nino}/self-employments using a different nino than that on the organisation user.

Expected Outcome:
400 NINO_INVALID

Actual Outcome:
403 CLIENT_NOT_SUBSCRIBED

The issue with this error not being NINO_INVALID is that we don't know whether the user has simply entered the wrong NINO number, or if they are genuinely not subscribed to the MTD self-assesment-api. If the NINO is wrong we want to allow them to change the NINO, if they are not subscribed we want to send them the link to subscribe. We can't differentiate if the error is the same.

Will this behaviour be the same in production as it is in sandbox?

**Comment by dabd** [comment]
Hi @DBrown2207, if you do OAuth with a given user and use another valid NINO to call an endpoint, it is expected that you get 403 CLIENT_NOT_SUBSCRIBED, as that NINO is valid but not associated with the authorised user.  The error code 400 NINO_INVALID is reserved for validating the formatting of the NINO identifier, not to check the association of the authorised user with the NINO.
Thanks, I hope this helps.

**Comment by alexec** [comment]
Thank Dario - can I please ask, how do we differentiate (a) the user has entered the wrong NINO from (b) they entered the correct NINO, but are not subscribed? 

We want to be able to deal with differently. In case (a) ask the user to check their NINO and in case (b) tell them they need to subscribe. Is that possible?

**Comment by dabd** [comment]
Hi Alex,

I believe your question is related to [this one](https://github.com/hmrc/self-assessment-api/issues/530).  To differentiate between the two cases you would have to be able to query the NINO for an authorised user, which we currently don't do.  Can you please raise this with  SDSTeam@hmrc.gsi.gov.uk?

**Comment by DBrown2207** [comment]
Hi @dabd,

I think that although related, we do not need to be able to query the NINO for this to work.

The error code being returned is CLIENT_NOT_SUBSCRIBED, however the client is subscribed so this error code is wrong.

When the NINO in the url does not match the NINO for the user, we should get some different error. We do not need to query the NINO to solve this, just a different error code.

**Comment by dabd** [comment]
Hi @DBrown2207, @alexec,

We are going to have a discussion about this issue within the team in the next few days and we will get back to you on this. Thanks.

**Comment by DBrown2207** [comment]
Hi @dabd, has there been any discussion on this yet?

**Comment by nvasilev-hmrc** [comment]
Hi @alexec, @DBrown2207,

Apologies for the delay in our response, it was my fault. 

We would really like to help you increase the usability of your application, but after careful consideration of the questions which you raised, we believe that the error codes which are currently in place do not need amendment. 

Please find the reasons for that decision below:

> the user has entered the wrong NINO
From API point of view, this would mean that the currently logged-in user is trying to access the resources of some other person on the HMRC Platform, via using his/her NINO. For this attempt `CLIENT_NOT_AUTHORISED` seems as a valid response from _security perspective_ - it does not reveal further details about the requested NINO. 

> how do we differentiate (a) the user has entered the wrong NINO from (b) they entered the correct NINO, but are not subscribed?
Right now we are not aware of a way to programmatically validate the NINO of the logged in user, but we are reaching out to other teams in HMRC trying to find out more information on that. Once we have clarity we will leave a comment under this discussion. 

> We want to be able to deal with differently. In case (a) ask the user to check their NINO and in case (b) tell them they need to subscribe. Is that possible?
We are afraid not.

**Comment by DBrown2207** [comment]
@nvasilev-hmrc thanks for the update

**Comment by alexec** [comment]
Thank you for this.
