### ISSUE TITLE
What does no content 204 (http code) mean for calculation GET API 

### ISSUE THREAD

**Issue by sri-akshat** [hmrc/self-assessment-api#544]
When we hit /self-assessment/ni/{nino}/calculations/{taxCalculationId} api we get a 204 response. Does it mean that the calculation is not available and we should try again later OR does it mean that the calculationId supplied is incorrect and hence, no content ? How can I differentiate between the two scenarios.

**Comment by hicnar** [comment]
Hi,

In that case 204 is returned when the tax calculation for the given taxCalculationId is not ready yet. Once the calculation process has finished for the given taxCalculationId, 200 will be returned along with JSON containing the calculation results.

Hope that helps and sorry about long wait for that reply.
