### ISSUE TITLE
When will the retrieve self-employment business obligations API would return the obligations for the next financial year

### ISSUE THREAD

**Issue by audupa** [hmrc/self-assessment-api#548]
Currently the get business obligations API would list the obligations for current financial year for a given self employment business.
We wanted to know when this API would provide us the next financial year's obligations. I am guessing it's when all the obligations for the current financial year is met. 
Correct me if this understanding is wrong.

**Comment by rgladwell** [comment]
We are consulting our back-end systems for confirmation about this. We may not get a reply until the new year due to annual leave over the holiday season.

**Comment by audupa** [comment]
Thanks @rgladwell

**Comment by audupa** [comment]
Hi @rgladwell Did you get a chance to confirm on the behavior from the back-end team?

**Comment by audupa** [comment]
Could someone please help us in clarifying our question?

**Comment by audupa** [comment]
Hi, Could anyone please reply on this question?

**Comment by MarkAKelly** [comment]
Hi @audupa, I assume your still after a response to this question?  I'll chase this up for you now and try and get back to you later today.

**Comment by MarkAKelly** [comment]
Hi @audupa, for SA the Get Business Obligations endpoint returns obligations _that have been created_ for that yearly accounting period.  Current practice is that a new obligation is created as the last one is fulfilled.  This will change for the 18/19 tax year where the four quarterly periodic obligations will be created on the first day of the accounting year for that business.

Hope that helps.

**Comment by audupa** [comment]
Thanks @MarkAKelly
