### ISSUE TITLE
IV process and possible IV errors returned

### ISSUE THREAD

**Issue by CapraGenus** [hmrc/self-assessment-api#562]
Not an issue per say but just wanted to know if you guys are able to supply a list of the possible IV error codes that get passed back to applications upon IV failure.

Can't for the life of me find any documentation on this. (Can find API specific docs but not any IV docs)

For reference, I am referring to the IV errors such as IDENTITY_VERIFICATION_PRECONDITION_FAILED which are passed back within a redirect URI. If you do indeed have any documentation I would be grateful.

**Comment by hicnar** [comment]
Here is the list of possible errors:

IDENTITY_VERIFICATION_INCOMPLETE
IDENTITY_VERIFICATION_FAILED_MATCHING
IDENTITY_VERIFICATION_INSUFFICIENT_EVIDENCE
IDENTITY_VERIFICATION_LOCKED_OUT
IDENTITY_VERIFICATION_USER_ABORTED
IDENTITY_VERIFICATION_TIMEOUT
IDENTITY_VERIFICATION_TECHNICAL_ISSUE
IDENTITY_VERIFICATION_PRECONDITION_FAILED

Hope this helps!

**Comment by CapraGenus** [comment]
IDENTITY_VERIFICATION_TECHNICAL_ISSUE
I am assuming this is when server has gone boom and or 503 is returned

IDENTITY_VERIFICATION_PRECONDITION_FAILED
Any hints on this on?

The other though, thank you much appreciated, a lot quicker getting answers from here.

**Comment by hicnar** [comment]
Trying to get some more info on that one.
Stay tuned!

**Comment by hicnar** [comment]
So, I contacted the team that maintains IV, in response I got pointed to the following url:

https://test-developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints 

In there, there is the following sentence which may be particularly useful: "The full list of error codes can change over time, and we therefore recommend that developers do not cater for specific error codes."

**Comment by CapraGenus** [comment]
Ha, great. That's ok I guess, just want to cater for it because we don't want users being sent to our redirect URI only to be confused as to what happened.

Thanks for the help though, makes my life easier :)
