### ISSUE TITLE
Application not accessed more than 60 days

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/self-assessment-api#581]
There was an email explaining applications that hadn't been accessed for more that 60 days were moved to some new location (I don't remember the full details now). But basically we need to something first. What is it we are meant to do?

When VAT was moved to an earlier date than self-assessment, developer time priorities  were changed we stopped all things MTD for a few months. Now it looks like it's time to resurrect the project but something broken and I think it's the bit I have tried to recall.

Please remind me

**Comment by jacobbrownlow** [comment]
Hi @mathiasbanda 

I am not aware of this email or any migration/movement of services. If you are experiencing any issues please let us know, or contact Software Developers Support Team on SDSTeam@hmrc.gsi.gov.uk for more information about the email you received.

Regards, Jacob

**Comment by mathiasbanda** [comment]
Thanks @jacobbrownlow that's no longer an issue.
