### ISSUE TITLE
Error calling oauth/token in the sandbox

### ISSUE THREAD

**Issue by steve-bartlett** [hmrc/self-assessment-api#587]
I am getting lots of errors when calling the following endpoint in the sandbox:

POST https://test-api.service.hmrc.gov.uk/oauth/token

Response: StatusCode: 500, ReasonPhrase: 'Internal Server Error'

Response Body: {"error":"server_error","error_description":"An unexpected error occurred"}

This has been working for some time but has been intermittently failing for the last few days, is this being worked on?

If this is not the correct forum can you please forward

Thanks

**Comment by narendravijayarao** [comment]
Hi Steve,

Thank you for your question, unfortunately we cannot answer this question as it relates to the wider HMRC API Plaform and is not exclusive to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience.
Narendra.

**Comment by dvdfmiller** [comment]
Hi,
I am getting the same error - HTTP response code: 500:

`org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.IOException: Server returned HTTP response code: 500 for URL: https://test-api.service.hmrc.gov.uk/oauth/token`

thanks
David

**Comment by dvdfmiller** [comment]
Hi,
All OK now.

It's working today and I no longer get this error - HTTP response code: 500

many thanks
David
