### ISSUE TITLE
Will the accountingPeriod dates change to the current accountingPeriod at some point

### ISSUE THREAD

**Issue by steve-bartlett** [hmrc/self-assessment-api#588]
When I call this endpoint:
/self-assessment/ni/{nino}/self-employments/{selfEmploymentId}

I get back the self employment details, for example 

{
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
etc...
}

Will the accountingPeriod dates change to the current accountingPeriod at some point ie: if I make the call on 2018-04-06?
Or is this dependent on the state of the previous accounting period or the current date?

I could not find any mention of what the behavior will be in the documentation.

Thanks

**Comment by jacobbrownlow** [comment]
Hi Steve

My understanding is that the Accounting Period is provided by the user upon registration/subscription, and will be used to determine the Obligation Periods.

Unfortunately we cannot tell you if the Accounting Period will change as it relates to the wider programme. This channel is only of specific questions relating to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
Jacob
