### ISSUE TITLE
Internal server error (500) on submitting test VAT return a second time

### ISSUE THREAD

**Issue by paulvickery** [hmrc/self-assessment-api#610]
I have used the test API to submit a VAT return, which is fine. Submitting the same period again for the same VRN gives a 500 error, instead of the 403 DUPLICATE_SUBMISSION which we were expecting.

**Comment by westwater** [comment]
Hey @paulvickery 

You will need to supply the DUPLICATE_SUBMISSION gov test scenario header. We have a bug on the backlog for the 500 error.

**Comment by paulvickery** [comment]
OK, thanks. What are timescales for the fix?

**Comment by paulvickery** [comment]
I'm actually getting a 500 error on any submission now, not just the second time.

Any news on when this will be fixed?

**Comment by kityasisrishu** [comment]
obligations :-
{
"obligations":[{"start":"2017-04-01","end":"2017-06-30","due":"2017-08-06","status":"F","periodKey":"#001","received":"2017-06-25"},
{"start":"2017-07-01","end":"2017-09-30","due":"2017-11-06","status":"O","periodKey":"#002"},
{"start":"2017-10-01","end":"2017-10-31","due":"2017-12-07","status":"O","periodKey":"#003"}
]
}

post data;_
{
  "periodKey": "#001",
  "vatDueSales": 100.00,
  "vatDueAcquisitions": 100.00,
  "totalVatDue": 100.00,
  "vatReclaimedCurrPeriod": 100.00,
  "netVatDue": 100.00,
  "totalValueSalesExVAT": 500,
  "totalValuePurchasesExVAT": 500,
  "totalValueGoodsSuppliedExVAT": 500,
  "totalAcquisitionsExVAT": 500,
  "finalised": true
}


Response :-
{ "code" : "INVALID_SCOPE", "message" : "Can not access the required resource. Ensure this token has all the required scopes." }

**Comment by westwater** [comment]
@kityasisrishu When you set up your test user you needed to grant read/write access to your vendor application.

here is an example of the url to use (note the scope query string)
https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=<CLIENT_ID> &scope=read:vat+write:vat&redirect_uri=<REDIRECT_URI>&state=12345

**Comment by westwater** [comment]
I will be closing this ticket now as there is a bug on the backlog to fix this.
