### ISSUE TITLE
Production VAT obligations date range

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/self-assessment-api#623]
In production then, does the minimum 6+ months date range apply for retrieving the obligations? Or will a proper quarter 1st April 2018 to 30 June 2018 work?

We need to know this because until we try it live it's so far untested and it would be very helpful to know ASAP please

**Comment by jacobbrownlow** [comment]
Hi @mathiasbanda 

There is no minimum date range for VAT obligations requests in Production. 

Previously there was a bug in our test environments that meant a minimum 6 month range was required. This has now been fixed.

Please use https://github.com/hmrc/vat-api/issues for any further vat questions

Regards, Jacob
