### ISSUE TITLE
retrieve calculation and retrieve validation messages returns error that this api is no longer available use v2.0... can any one explain that why it is happening...

### ISSUE THREAD

**Issue by Mushtaq009** [hmrc/self-assessment-api#695]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the Self-Assessment-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

* **I'm submitting a ...**
  - [ ] Bug - API
  - [x] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

* **What is the expected behaviour?**

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MeliaDavies** [comment]
Hi @Mushtaq009 

The reason why you are receiving this is because the backend no longer supports V1.0 for these endpoints. 

Thanks

**Comment by Mushtaq009** [comment]
> Hi @Mushtaq009
> 
> The reason why you are receiving this is because the backend no longer supports V1.0 for these endpoints.
> 
> Thanks sir but i am already using v2.0 and still return the same error...

**Comment by Mushtaq009** [comment]
uhhh my mistake... thanks alot sir i was passing header v1.0 header
