### ISSUE TITLE
Self Assessment Making Tax Digital UTR wrong format

### ISSUE THREAD

**Issue by phani29oct** [hmrc/self-assessment-api#712]
Hi Team,

While I am working with Self Assessment Making Tax Digital and fetching Test Users using SandBox API. I am able to fetch the user details in that UTR format is "Y596379780" but in the developer hub test result it is displaying as "1000057161"

After using this UTR I am getting response as "SA_UTR_INVALID"

![1](https://user-images.githubusercontent.com/42927480/55400608-f1e9be00-556b-11e9-9042-a825f69fba1e.PNG)

![2](https://user-images.githubusercontent.com/42927480/55400617-fb732600-556b-11e9-8684-4c583ab9bf31.PNG)

Can anyone help me on this

Thanks for the help in advance

**Comment by jeremystone** [comment]
Thanks. This should now have been fixed.

**Comment by phani29oct** [comment]
Hi jemerystone,

Thanks for your response. Now I am able to fetch the correct format of SA UTR
