### ISSUE TITLE
Response not receiving from HMRC

### ISSUE THREAD

**Issue by phani29oct** [hmrc/self-assessment-api#713]
Hi Team,
As we are trying to retrieve the data from HMRC for MTDfB SA using sandbox users from given in HMRC website. I am receiving only one response every time it is 
{
    "code": "NOT_FOUND",
    "message": "The requested resource could not be found."
}

why I am unable to retrieve the info from HMRC.
Can anyone help me on this

Thanks in advance

**Comment by jeremystone** [comment]
Do you know which endpoint URL you are using that is giving this response?

**Comment by phani29oct** [comment]
Hi Jeremystone

Thanks for your response, below are the end point url's I am using to fetch the response

1. https://test-api.service.hmrc.gov.uk/individual-income/sa/{utr}/annual-summary/2016-17
2. https://test-api.service.hmrc.gov.uk/marriage-allowance/sa/{utr}/status
3. https://test-api.service.hmrc.gov.uk/national-insurance/sa/{utr}/annual-summary/2016-17
4. https://test-api.service.hmrc.gov.uk/individual-tax/sa/{utr}/annual-summary/2016-17
5. https://test-api.service.hmrc.gov.uk/individual-employment/sa/{utr}/annual-summary/2016-17
6. https://test-api.service.hmrc.gov.uk/individual-benefits/sa/{utr}/annual-summary/2016-17

Thanks in advance

**Comment by jeremystone** [comment]
Unfortunately these are not MTD endpoints.

You should contact SDSTeam@hmrc.gov.uk who should be able to point you in the right direction.

**Comment by phani29oct** [comment]
Hi Jeremystone,

Thanks for your response, those are the endpoints given in below mentioned location.

In the above mentioned URL I have mentioned the tax year (**2016-17**) in the place of **{taxYear}**

So these are the end points I am using to fetch the info from HMRC for benefits

https://developer.service.hmrc.gov.uk/api-documentation/docs/api?filter=self-assessment

As a developer I am using to connect to HMRC by using sandbox URL

https://test-api.service.hmrc.gov.uk

![image](https://user-images.githubusercontent.com/42927480/55471770-202cd380-5628-11e9-8f8e-6cf53065cd53.png)


![image](https://user-images.githubusercontent.com/42927480/55471517-8a914400-5627-11e9-91c6-b11bf17b7772.png)


1. **For Individual Benefits API it was given as** 

![image](https://user-images.githubusercontent.com/42927480/55470974-63864280-5626-11e9-96b7-489ee8fdd22e.png)

2. **For Individual Employment API it was given as** 

![image](https://user-images.githubusercontent.com/42927480/55471123-aea05580-5626-11e9-8730-3860cd8d9171.png)

3. **For Individual Income API it was given as** 

![image](https://user-images.githubusercontent.com/42927480/55471212-e0b1b780-5626-11e9-8ebc-82f94b682160.png)

4. **For Individual Tax API it was given as** 

![image](https://user-images.githubusercontent.com/42927480/55471307-1060bf80-5627-11e9-808d-99eb0bd30fcf.png)

5. **For Marriage Allowance API it was given as** 

![image](https://user-images.githubusercontent.com/42927480/55471381-3d14d700-5627-11e9-9ee6-a753efde62a6.png)

6. **For National Insurance API it was given as** 

![image](https://user-images.githubusercontent.com/42927480/55471437-6170b380-5627-11e9-8ea6-19c50cf2b77f.png)




Any help will be much appreciated!

**Comment by jeremystone** [comment]
This Github repo is for the Self-Assessment (MTD) APIs (see (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/mtd-income-tax-service-guide)).

Perhaps you should be using these APIs instead.

**Comment by phani29oct** [comment]
Hi jeremyStone,

Thanks for your response. I will check them and get back to you, if any queries

**Comment by phani29oct** [comment]
Hi jeremystone,

I have gone through the URL's given https://developer.service.hmrc.gov.uk/api-documentation/docs/api/mtd-income-tax-service-guide and I am receiving a blank response

I am taking the test user which was given in the sandbox in the same url

**Comment by daniel-andrews1994** [comment]
Hi @phani29oct

Unfortunately we are unable to help you with this issue, please take a look at this document to ensure you are taking the correct steps to use our APIs.
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0

If you are still having issues, please contact SDSTeam@hmrc.gov.uk as they will be able to help you with them.

Thanks

**Comment by phani29oct** [comment]
Hi,

I have gone through the API's given in the document for all the API's scope given in the document as "**read:self-assessment**" 
My query is should we call these all endpoints at single instance or can we have multiple calls for multiple endpoints

**Comment by mtd-api-team** [comment]
Hi @phani29oct - you can call the endpoints as many times as you want. Are you specifically asking about endpoints in this repository, or MTD endpoints in general?

**Comment by shaunl23** [comment]
I'm receiving a response of '[ ]' when calling the Get Self Employments endpoint. I just presumed the sandbox data wasn't available yet

**Comment by mtd-api-team** [comment]
@shaunl23 have you used the Sanbox only 'Create Self Employment Business'?  

Some of the endpoints are still stateful and require you to create the business to then use on subsequent endpoints.

**Comment by shaunl23** [comment]
Hi @mtd-api-team , thanks for the prompt reply.
I haven't. I started by creating a test user, then used their Nino and went through the authorisation.
I then started with the first endpoint, List all Self-Employment Businesses. I thought it would have test data already, but should I be doing the Add a self-employment business [test support] endpoint first to create the data?

Thanks :)

**Comment by mtd-api-team** [comment]
No problem @shaunl23,

Yes the general flow at the moment would be `OAuth` -> `Create test user using test only endpoint` -> `Use API endpoints`.  Some of our newer endpoints (Tax Calc, Dividends, Savings Accounts etc) won't require stateful user information and work primarily from Gov Test Scenario headers.

For the most part you can use the business created with the sandbox only endpoint.

Hope this helps!

**Comment by shaunl23** [comment]
Ah, that's great! Thank you for your help and clearing this up!
