### ISSUE TITLE
Marriage allowance API

### ISSUE THREAD

**Issue by IainWardle** [hmrc/self-assessment-api#721]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the Self-Assessment-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

* **I'm submitting a ...**
  - [X] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**
We are getting 500 Internal Service error calling both marriage allowance endpoints in the sandbox, this started happending a few weeks ago, can you confirm these endpoints are working.
* **What is the expected behaviour?**

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mtd-api-team** [comment]
This repository is related to the MTD Self-Assessment API. The Marriage Allowance API is a separate API. 

In any case we would recommend that you contact SDSTeam@hmrc.gov.uk who hopefully will be able to help you.
