### ISSUE TITLE
Error 500 Dividends

### ISSUE THREAD

**Issue by shaunl23** [hmrc/self-assessment-api#732]
Hi,
I'm receiving an error 500 when requesting or putting Dividends Income:

https://test-api.service.hmrc.gov.uk/self-assessment/ni/RH857982D/dividends/2017-18

Does anyone know what this could mean please?

**Comment by mtd-api-team** [comment]
Hi @shaunl23,

We just tried on our side and it is giving the expedted response. Can you please provide more information like headers, body, and Gov-Test-Scenario, to identify the issue.

Thanks...

**Comment by shaunl23** [comment]
Figured it out...

Where the other endpoints use Gov-Test-Scenario and "-", this one requires the header simply not be included to return the values :)
