### ISSUE TITLE
Intent To Crystallise - Missing Credentials

### ISSUE THREAD

**Issue by shaunl23** [hmrc/self-assessment-api#734]
* **I'm submitting a ...**
  - [x] Support request

Hi,
I have just about everything else in the API running ok, but when I post intent to crystallise I'm getting the error: Missing Credentials - Authentication information is not provided.

I'm using the same process as my other POST routines which all work.

OauthCall = HttpWebRequest.Create("https://test-api.service.hmrc.gov.uk/" & "self-assessment/ni/" & NINO & "/" & taxyear & "/intent-to-crystallise")

 OauthCall.Method = "POST"
            OauthCall.ContentType = "application/json"
            OauthCall.Accept = "application/vnd.hmrc.2.0+json"
            OauthCall.Headers.Add("Authorization", "Bearer " + it_token)

The post data is nothing ("")
The endpoint DOES work with the appropriate response if I use the test data headers NO_SUBMISSIONS_EXIST or FINAL_DECLARATION_RECEIVED, but I was wanting to test generating a crystallisation calculation, and then the endpoint to view it.

Can anyone offer any help please?

Thanks

**Comment by mtd-api-team** [comment]
Hi @shaunl23,

That's an interesting one - the only thing I can think of at the moment is that this endpoints returns a 303 (See Other) status with the resource location of the calculation created.  

I know from our experience that some HTTP clients will automatically redirect, so could it be possible that you are redirecting to the calculation resource without the credentials set on the request?

I can look through the logs with a bit more detail if you let me know when you made the requests, or aternatively try again and we can look at those going through.

**Comment by shaunl23** [comment]
Hi,

I have just made a request again (11:25) https://test-api.service.hmrc.gov.uk/self-assessment/ni/AP150501A/2017-18/intent-to-crystallise
if you wouldn't mind checking it for me.

Thank you

**Comment by mtd-api-team** [comment]
Brilliant, glad that we could help!
