### ISSUE TITLE
SAMTD/Individual Benefits

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#735]
In Self-Assessment  of MTD ,we are doing submissions of individual benefits .so we are facing issue  that "DATA SOURCE NOT FOUNd".so I  need support in this.

**Comment by mtd-api-team** [comment]
So that we can help you further, please can you confirm which MTD endpoint you are using, and what error response you are receiving.

**Comment by heythisiskishore** [comment]
This is the MTD Endpoint of individual Benefits:
https://test-api.service.hmrc.gov.uk /individual-benefits/sa/{utr}/annual-summary/{taxYear} 
We are sending request headers as per HMRC API Documentation
Accept : application/vnd.hmrc.1.1+json
Authorization:read:: Bearer bb7fed3fe10dd235a2ccda3d50fb
 If we send the headers in this way
 we are getting  following response
{
    "code": "INVALID_SCOPE",
    "message": "Can not access the required resource. Ensure this token has all the required scopes."
}

If we send the headers in this way  
Accept : application/vnd.hmrc.1.0+json
Authorization:read:: Bearer bb7fed3fe10dd235a2ccda3d50fb

we are getting the following response:
{
    "code": "NOT_FOUND",
    "message": "The requested resource could not be found."
}
For all the endpoints we are getting same response.

Thanking you

**Comment by mtd-api-team** [comment]
Unfortunately individual-benefits is not one of the endpoints handled by this repository (Self Assessment (MTD)).

You should contact SDSTeam@hmrc.gov.uk who will hopefully be able to help you with your issue.
