### ISSUE TITLE
clarification whether [Test Support] is only for the developers usage in sandbox

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#742]
We are using [Test Support] API to post the business details and then whilst retrieving the self employment id in [API name] we are getting the same business details which we had post earlier.

We need a clarification whether [Test Support] is only for the developers usage in sandbox for testing or else it is going to be used in production environment as well for live user (Sole Traders).

End Point : Add a self-employment business [test support]
URL : https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#selfemployment-business_add-a-selfemployment-business-test-support_post_accordion

Please provide the clarification on the same.

Awaiting your response!

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore,

There are no plans for this to be used in the production environment. This API is only available to facilitate testing in the sandbox environment.
An API marked as [test only] indicates that it is currently available in the test environment but will eventually be released in the production environment.
[test support] indicates that it is used in the test environment only.

I hope that clears it up.

Thanks,
@mtd-api-team
