### ISSUE TITLE
Regards CLIENT_NOT_SUBSCRIBED

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#745]
Hi Team,

I have created a Test Company in the Sandbox environment.. 

I got the list of details like user id, password,address details, VRN and NINO Number etc.

In this i got the NINO as **'AB123456C'**. 

I have successfully authorised this NINO number,  but while retrieving the list of Businesses for Self-Employment it is throwing an error like 

HTTP status: 403 (Forbidden)
Code: CLIENT_NOT_SUBSCRIBED.

This is throwing the error while using the following link

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#selfemployment-business_add-a-selfemployment-business-test-support_post_accordion

The same scenario for other NINO number is working fine.

Any help or guidance would be much appreciated!

Thanks in advance.

**Comment by heythisiskishore** [comment]
Hi there,

In the above situation, we have got the NINO as "AB123456C" and the same is throwing an error message. Could you please advise what would be the possible reason for the same.

Any help on the above query would be much appreciated.

Awaiting your response!

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

Apologies for the delay.

The nino generation in the test environment should be randomised, so we would not expect `AB123456C` to be returned. It looks like something went wrong with the test user setup, but I can't be sure. Let us know if this happens again.

Thanks
