### ISSUE TITLE
Regards Obligations Met and Not met in Quarterly Submissions.

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#746]
Hi there, 

In Self-Employment Endpoint : List all self-employment businesses
while retrieving the business and accounting period, initially we are getting one accounting period in a year only like

[
  {
    "id": "{selfEmploymentId}",
    "accountingPeriod": {
      "start": "2017-04-06",
      "end": "2018-04-05"
    },
    "accountingType": "CASH",
    "commencementDate": "2016-01-01",
    "cessationDate": "2018-04-05",
    "tradingName": "Acme Ltd.",
    "businessAddressLineOne": "1 Acme Rd.",
    "businessAddressLineTwo": "London",
    "businessAddressLineThree": "Greater London",
    "businessAddressLineFour": "United Kingdom",
    "businessPostcode": "A9 9AA"
  }
]

We have referred it from below link: 

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#selfemployment-business_list-all-selfemployment-businesses_get_accordion

but in future how can we get the data (which format) for next accounting period? 

Do we need to call the another API to get new accounting period i.e.

/self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/obligations

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#selfemployment-business_get-a-selfemployment-business_get_accordion

In Self-Employment Endpoint : Retrieve self-employment business obligations.

After retrieving the obligation periods, we are getting the four quarters in the testing environment, For the first quarter it is showing as met but we are able to submit the transaction for the first period. For subsequent quarters if we submit the transaction to the HMRC the status is not changing to met (still the periods are showing in the Not met status only).

If the First Quarter is not Submitted then we cant submit the Second Quarter, if we will do it forcefully then we will get the issue like '**NOT_CONTIGUOUS_PERIOD**'.

As a suggestion, Could you please provide more accounting periods and obligations in sandbox as we will be having in Production environment. It will be very helpful for the developers to test the same in multiple scenario's, or make a replica of the Production Environment as the Sandbox environment.

Any help would be much appreciated!

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

The endpoints you are using are a mixture of stateful and canned responses (in the testing Sandbox).

The test support endpoint "Add a self-employment business" enables you to create an accounting period of your choosing. You must then submit the first periodic summary beginning with the same date your accounting period starts.

These endpoints will store your submissions. However "Retrieve Obligations" will not update according to your submissions. The default response from Retrieve Obligations is 1 met and 3 open, using the dates you have supplied in your accounting period. There are additionally 2 more responses available by using Gov-Test-Scenarios. 

Again, these won't update in response to your submissions and are limited to 3 success scenarios. The intended purpose of this environment is to demonstrate example responses and test connectivity through the API Platform. Unfortunately we cannot emulate a Production like environment.

You must supply periodic summaries in a contiguous order, for example:
`2018-04-06_2018-07-05` must be followed by `2018-07-06_2018-10-05` without gaps.

I do not believe there is a way to extend the accounting period, for example into the next tax year, once you have submitted them for this business. You will need to create a new test user.

Regards

**Comment by heythisiskishore** [comment]
Hi Team,

In continuation of your earlier response, in sandbox environment do we need to submit the first quarter which already has a **'MET'** status?

Any help would be much appreciated.

Thanks

**Comment by mtd-api-team** [comment]
@heythisiskishore 

Apologies for the delay.

The periodic and annual summary endpoints for SA-API are stateful, and therefore you will need to submit the first quarter.

The obligations responses are canned (not stateful) and return hard coded example responses. They will not represent the current state of your periodic submissions.

Regards
