### ISSUE TITLE
FHL and Other property

### ISSUE THREAD

**Issue by johnhemming** [hmrc/self-assessment-api#748]
I am trying to reconcile the JSON in the FHL and Other property submissions to the form SA105 which is the non MTD form that is completed for property.

I have already reconciled the JSON for self-employments and that reconciles substantially properly although not perfectly.

However, the JSON in FHL and Other property does not really reconcile.  Taking FHL
The form has: (with box numbers)
5 Income (and allowance)
6 Rent paid, repairs, insurance and costs of services provided
7 Loan interest and other financial costs
8 Professional fees
9 Other allowable expenses
10 Private use adjustment.
11 Balancing charges
12 Capital Allowances

The JSON has:
    "premisesRunningCosts": { "amount": 100.25 },
    "repairsAndMaintenance": { "amount": 100.25 },
These two are box 6

    "financialCosts": { "amount": 200.25 },
This is box 7
    "professionalFees": { "amount": 100.25 },
This is box 8
    "travelCosts": { "amount": 100.25 },
This does not seem to be something that should be anywhere for property
    "costOfServices": { "amount": 100.25 },
This does not look right.
    "residentialFinancialCost": { "amount": 200.25 },
This is probably box 10 (but that would not really be an expense anyway)

    "broughtFwdResidentialFinancialCost": { "amount": 100.25 },
I am not sure where this comes from
    "other": { "amount": 100.25 },
This would be box 9
    "rarReliefClaimed": { "amount": 100.25 }
Not sure what this is.

Is there an explanation as to how one compares the figures in the form SA105 to the data in MTD or is it simply that property has not really been finalised yet and this will probably happen at a later stage so one should simply treat the items as to some extent placemats.

**Comment by mtd-api-team** [comment]
Hi John,

We will take a look into this matter and get back to you as soon as possible.

**Comment by mtd-api-team** [comment]
Hi @johnhemming 

Apologies for the delayed response. We are not in a position to provide this level of business detail regarding the fields and how to complete your submissions. These questions are best handled by the Software Development Support Team (SDST) who you can contact at SDSTeam@hmrc.gov.uk

Regards
