### ISSUE TITLE
Regards 'Irrecoverable debts written off' (badDebt) accepting values

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#751]
Dear Team,

While submitting the Quarterly Submissions for the Self-employment business, it is throwing an error message while submitting the 'Irrecoverable debts written off' with negative value. **As per the document in the developers hub it has to accept negative value but it is not doing so.** For further information on this please find the attached images.

Can you guys please confirm this from your end.

As a Suggestion can you (HMRC) make the sandbox environment similar to the Production Environment for easy and effective results.

![Untitled1](https://user-images.githubusercontent.com/47594030/64060008-650f6300-cbe4-11e9-900f-ef477b559afd.png)
![Untitled2](https://user-images.githubusercontent.com/47594030/64060009-650f6300-cbe4-11e9-915e-3f916764429f.png)
![Untitled3](https://user-images.githubusercontent.com/47594030/64060010-65a7f980-cbe4-11e9-94c2-0774f27e6ec5.png)

**Comment by heythisiskishore** [comment]
Hi there,

Any help on the above problem would be much appreciated.

Thanks

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

Apologies for the delayed response.
We're aware of this issue and there is a story on our backlog to fix it.

Thanks

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

This should now be resolved. Let us know if you find any issues.

Thanks
