### ISSUE TITLE
UK Property Accounting Period Dates and Obligation Dates

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#769]
Dear Team,

We are working on the UK Property related Test API's.

By using the below link we have created a Test Business for submitting the UK Property related data

[(https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#uk-property-business_add-a-uk-property-business-test-support_post_accordion)]

The above link generates a **Accounting period** with **"start": "2017-04-06" and "end": "2018-04-05"**

but while retrieving the Obligations for the Accounting period it is sending the different obligation dates of different Accounting Period in the Sandbox environment which is as follows.

[(https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#uk-property-business_retrieve-all-uk-property-business-obligations_get_accordion)]

{
  "obligations": [
    {
      **"start": "2019-04-06",
      "end": "2019-07-05",
      "due": "2019-08-05",**
      "met": true
    },
    {
      **"start": "2019-07-06",
      "end": "2019-10-05",
      "due": "2019-11-05",**
      "met": false
    },
    {
      **"start": "2019-10-06",
      "end": "2020-01-05",
      "due": "2020-02-05",**
      "met": false
    },
    {
      **"start": "2020-01-06",
      "end": "2020-04-05",
      "due": "2020-05-05",**
      "met": false
    }
  ]
}

Here we are getting the different Obligations which is not with in the Accounting Period dates which we have mentioned in the above with bold. So if it is like this, then how can we submit the UK Property related information and EOPS for the Accounting Period?

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

The sandbox test data should be fixed to 2017-18 (for these older SA-API endpoints), and we are not able to replicate retrieving obligations for 2019-20.

I have just tried the sandbox, and I can only return 2017-18
```{
    "obligations": [
        {
            "start": "2017-04-06",
            "end": "2017-07-05",
            "due": "2017-08-05",
            "met": true
        },
```

I'd be interested in knowing if and how you retrieved 2019-20 if you could offer any more info?

However, the obligation endpoint is canned (stateless) data and is not linked to the periods in the sandbox, so you can continue to submit 2017-18 periods and it should be work.

Let us know if you have any further questions.

Regards, MTD API team

**Comment by heythisiskishore** [comment]
Dear Team,

Please find the attached image for your information. It is happening only for the given NI number. Other NINO's are working fine.

![UKObligations](https://user-images.githubusercontent.com/47594030/75646127-95f15300-5c6e-11ea-98dc-8ca5e2cc3533.JPG)

**Comment by heythisiskishore** [comment]
Dear Team,

Is it compulsory to submit the Non FHL and FHL related data or can we do either any one of them individually?

**Comment by heythisiskishore** [comment]
The issue is raising again and again the same.

Can you please check again.

Accounting period is 06/04/2017 to 05/04/2018

but the obligations are in the year 2019-20.

**Comment by heythisiskishore** [comment]
Please check with the NINO 

ZW596334A
OR310633B

in the sandbox environment.

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore

A UK Property user can submit either FHL or Non-FHL only, or both, to fulfil their obligations.

As for the 2019-20 Obligations issue in Sandbox, we cannot replicate this. The accounting period in Sandbox is hard coded to 2017-18, and the Obligations are generated from these dates. 

Can you let us know if this is happening with NEW test users, or old ones?

Regards
