### ISSUE TITLE
UK Property - BOTH FHL+Non FHL together as a Source of Income

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#771]
Can a person have **BOTH (FHL+Non FHL)** Furnished Holiday Lettings and Non Furnished Holiday Lettings as Source of Income.

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

Yes this is correct. A single property income source can have either, or both.

Regards

**Comment by heythisiskishore** [comment]
Thanks for a quick and useful response.

A little further to the trailing query - if a person have both FHL & Non FHL income - is End of Period Statement (EOPS) required to be submitted separately (for FHL & Non FHL) or in combination .

Regards

**Comment by mtd-api-team** [comment]
Hi, I have just answered this in https://github.com/hmrc/self-assessment-api/issues/772

Regards
