### ISSUE TITLE
EOPS - FHL & Non FHL 

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#772]
If a person have both FHL & Non FHL income - is End of Period Statement (EOPS) required to be submitted separately (for FHL & Non FHL) or in combination

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

If a UK Property has both FHL and Non-FHL periodic submissions, they would submit only one EOP Statement.

> Use this endpoint to finalise the end-of-period statement, for this accounting period, for a UK property business.

Regards
