### ISSUE TITLE
Regards Submission in VAT Submissions, Self-employment, UK Property

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/self-assessment-api#775]
Hi Team,

Can i Submit the same transactions of Incomes and Expenses in VAT, Self-employment and UK Property.

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

We're not in the best position to provide advice on tax and submissions, we can only give technical advice on how to use the self-assessment-api and vat-api.

Please contact the Software Developers Support Team at SDSTeam@hmrc.gov.uk for more help.

Regards
