### ISSUE TITLE
Summary data Amend requests are ignored in test environment

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/self-assessment-api#784]
Hi Team,
I am working on Year end Summary requests in your test environment .
Amends for Business and Property are processed correctly and new amounts are retrievable after logout-login.
Dividends and Savings Accounts amends are ignored and not retrievable after logout-login.
Is it by design?
However documentation page for these API calls does not mention "canned" responses.

Kind regards,
Alexei

**Comment by hmrc-api-team** [comment]
Hi @alexei-serjantov 

Unfortunately the MTD API development team has moved away from using "stateful" responses that return data you have submitted. 

When dividends and savings endpoints were built they were made "stateless" or "canned" meaning they will only return stubbed responses, regardless of what data you submit.

We have tried to add helpful info around this in the Test Data section, for example:
![image](https://user-images.githubusercontent.com/66629710/95596163-f2a6be80-0a44-11eb-9207-a80e3a80f5cd.png)

If it doesn't say anything like this it's safe to assume the responses will be canned.

Regards

**Comment by alexei-serjantov** [comment]
Thanks for clarification
