### ISSUE TITLE
Token server error

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/self-assessment-api#793]
- [x] Support request

Hi Team,

Today very often I  was  getting an error on token request: 
What should I do to avoid these errors ?

* **What is the current behaviour?**

  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'test-api.service.hmrc.gov.uk',
  trace: [
    {
      method: 'POST',
      url: 'https://test-api.service.hmrc.gov.uk/oauth/token'
    }
  ],
  isBoom: true,
  isServer: true,
  data: null,
  output: {
    statusCode: 502,
    payload: {
      message: 'Client request error: getaddrinfo ENOTFOUND test-api.service.hmrc.gov.uk',
      statusCode: 502,
      error: 'Bad Gateway'
    },
    headers: {}
  }

* **What is the expected behaviour?**

No error

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ac000** [comment]
Possibly some transient DNS issue... are you still seeing this? I've never hit it myself.
