### ISSUE TITLE
Service is down in Sandbox environment

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/self-assessment-api#795]
- [ x] Support request

* **What is the current behaviour?**

 self-assessment/ni/WB434474B/savings-accounts returns status code 500

* **What is the expected behaviour?**

 self-assessment/ni/WB434474B/savings-accounts  to return status code 200

**Comment by hmrc-api-team** [comment]
Hi @alexei-serjantov 

Apologies for this. One of the stubs that self-assessment-api relies on was down. It is back up now, and you should be able to successfully hit self-assessment-api now.

Regards
