### ISSUE TITLE
API calls for calc and EOPS return 500s in sandbox

### ISSUE THREAD

**Issue by adamfairstr** [hmrc/self-assessment-api#801]
I'm submitting a Bug - API

**What is the current behaviour?**

From this morning all calls to:

api/hmrc/v1/individuals/calculations/{nino}/self-assessment
api/hmrc/v2/self-assessment/ni/{nino}/self-employments/{selfemploymentid}/end-of-period-statements/from/{startDate}/to/{endDate}
api/hmrc/v2/self-assessment/ni/{nino}/savings-accounts

in sandbox are returning 500 internal server errors with this response body:

{"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}

* **What is the expected behaviour?**

These APIs return success codes and responses as per the documentation.

**Comment by hmrc-api-team** [comment]
Hi @adamfairstr

Thank you for bringing this to our attention. It looks like one of the stubs downstream to the self-assessment-api had gone down - I have reset it and requests to these endpoints should work again.

Please could you verify whether your calls to these endpoints return the expected responses now?

Kind regards

**Comment by alexei-serjantov** [comment]
Hi team,

It seems that "one of the stubs downstream to the self-assessment-api" goes
down from time to time
as the same issue was raised earlier as request #799.
I also noticed that self-assessment-api performance deteriorates with time.
For example: a test with 377 get calls took 457 sec to complete in the
morning before crash.
Now exactly same test takes 396 seconds.
Hope it helps.

Kind regards

**Comment by hmrc-api-team** [comment]
Hi @alexei-serjantov

It's a known issue with this stub that it goes down every so often, though we're currently unaware as to what causes it. Currently the workaround is for someone on the team to manually reset it on our end while we investigate the cause for the recent failures; if this happens again please don't hesitate to raise an Issue and we'll reset it for you.

I will raise the issue of performance deteriorating over time with our QA lead. Thank you for bringing this to our attention.

Kind regards

**Comment by adamfairstr** [comment]
All working. Thanks very much.
