### ISSUE TITLE
500s returned from many ITSA endpoints in sandbox

### ISSUE THREAD

**Issue by adamfairstr** [hmrc/self-assessment-api#802]
Bug

What is the current behaviour?

500s returned from many sandbox ITSA endpoints.

What is the expected behaviour?

Successful responses.

**Comment by hmrc-api-team** [comment]
Hi @adamfairstr

I believe this is the same issue as #801 - I've reset the offending stub, could you check if the calls are successful now? Apologies again for this.

Kind regards

**Comment by adamfairstr** [comment]
All working now thanks.
