### ISSUE TITLE
Some MTD ITSA API calls respond with 500s in sandbox

### ISSUE THREAD

**Issue by adamfairstr** [hmrc/self-assessment-api#803]
* **What is the current behaviour?**

These are the endpoints that we have noticed are returning 500s

v2/self-assessment/ni/{nino}/savings-accounts
v2/self-assessment/ni/{nino}/dividends/{taxYear}
v2/self-assessment/ni/{nino}/uk-properties/end-of-period-statements/obligations

* **What is the expected behaviour?**

Successful responses

**Comment by hmrc-api-team** [comment]
Hi @adamfairstr,

Apologies, we're having some ongoing issues #801 with our stub in sandbox which causes it to periodically become unavailable and produce this behaviour. I've reset it manually and it appears to be behaving properly, so you should be able to access these resources now. Please let us know if this happens again.

Cheers,
MTD-API-Team

**Comment by adamfairstr** [comment]
Fixed now. Thanks
