### ISSUE TITLE
Getting unexpected 500's in Sandbox? Please report them here.

### ISSUE THREAD

**Issue by hmrc-api-team** [hmrc/self-assessment-api#804]
There is a known issue with one of our downstream stubs where it periodically needs resetting.

Please use this issue to report unexpected 500's in the sandbox while we look into the cause of the failures, just so we can keep all of the reports in one place.

Known Issues related to this topic (at the time of writing): #801, #802, #803

**Comment by hmrc-api-team** [comment]
Hi @vinukmathews, this endpoint ([Say hello application](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-example-microservice/1.0#_say-hello-application_get_accordion)) is not maintained by the hmrc-api-team. Please contact SDSTeam, they should be able to help you. At a glance, it looks like you're providing an invalid Authorization token.

**Comment by hmrc-api-team** [comment]
Also the stub issue we were having in February has been fixed and the stub has been stable for a few months, so I'm closing this issue.

**Comment by vinukmathews** [comment]
Dear team,

Can you help me with this error.

My client side application is runnig at localhost:4200
My server side program runnig at localhost:3000

When i call server api (localhost:3000/userCall, which is used for HMRC api call) from my angular application, it gives CORS error.

Cam you help me to fix it.

Regards
