### ISSUE TITLE
404 when submitting self-employment periodic update

### ISSUE THREAD

**Issue by vitalcode** [hmrc/self-assessment-api#809]
Please help me to understand why I am getting 404 while trying to submit self-employment periodic update. 

* **What is the current behaviour?**

When creating self-employment periodic update I am getting 404 (Not Found) response

* **What is the expected behaviour?**

I am expecting to get 201 (Created) with Location and X-CorrelationId headers

* **Other information** 

**Request:**

POST: https://test-api.service.hmrc.gov.uk/self-assessment/ni/AX106447D/self-employments/XAIS12345678911/periods 

Accept:application/vnd.hmrc.2.0+json
Authorization:Bearer 734a8166fbbddf5f6afe8b25e8961286
Content-Type:application/json

body:

{
   "from":"2017-07-06",
   "to":"2017-10-05",
   "incomes":{
      "turnover":{
         "amount":12.02
      },
      "other":{
         "amount":14.05
      }
   },
   "expenses":{
      "costOfGoodsBought":{
         "amount":16.08,
         "disallowableAmount":18.11
      },
      "cisPaymentsToSubcontractors":{
         "amount":20.14,
         "disallowableAmount":22.17
      },
      "staffCosts":{
         "amount":24.20,
         "disallowableAmount":26.23
      },
      "travelCosts":{
         "amount":28.26,
         "disallowableAmount":30.29
      },
      "premisesRunningCosts":{
         "amount":32.32,
         "disallowableAmount":34.35
      },
      "maintenanceCosts":{
         "amount":36.38,
         "disallowableAmount":38.41
      },
      "adminCosts":{
         "amount":40.44,
         "disallowableAmount":42.47
      },
      "advertisingCosts":{
         "amount":44.50,
         "disallowableAmount":46.53
      },
      "businessEntertainmentCosts":{
         "amount":48.56,
         "disallowableAmount":50.59
      },
      "interest":{
         "amount":52.62,
         "disallowableAmount":54.65
      },
      "financialCharges":{
         "amount":56.68,
         "disallowableAmount":58.71
      },
      "badDebt":{
         "amount":60.74,
         "disallowableAmount":62.77
      },
      "professionalFees":{
         "amount":64.80,
         "disallowableAmount":66.83
      },
      "depreciation":{
         "amount":68.86,
         "disallowableAmount":70.89
      },
      "other":{
         "amount":72.92,
         "disallowableAmount":74.95
      }
   }
}

**Responce:**

404 (Not Found)

**Comment by vitalcode** [comment]
I understand that I need first to add a self-employment business using this endpoint:

/self-assessment/ni/{nino}/self-employments/{selfEmploymentId}

I was trying to rely on self-employment business id returned from Business Details API endpoint: /individuals/business/details/{nino}/list. 

I guess that data (self-employment business id) retuned from this endpoint is just hard-corded data that cannot be used for submitting periodic updates. It is correct?

What about real life (prod) scenario? Can we use self-employment business id returned from Business Details API to use for periodic update submission?

**Comment by ac000** [comment]
Oh dear. Yeah this looks fubar.

That URL should of course just be

```
/self-assessment/ni/{nino}/self-employments/
```

but doing that doesn't seem to have any effect, you still just get the canned response from

```
/individuals/business/details/{nino}/list
```

with neither the _businessId_ or the _tradingName_ reflecting the created employment.

Things seem to just be going from bad to worse...

**Comment by hmrc-api-team** [comment]
Responded here https://github.com/hmrc/income-tax-mtd-changelog/issues/3
