### ISSUE TITLE
Test env: unable to get self-employment update periods - MATCHING_RESOURCE_NOT_FOUND

### ISSUE THREAD

**Issue by anlar** [hmrc/self-assessment-api#831]
Hi, I'm trying to use self-employment API to work in test environment.
I have created test individual: `{ "userId": "651359909411", "nino": "WW202851A" }` and business details API shows their self-employment as:

```
{
    "businessId": "XAIS12345678901",
    "typeOfBusiness": "self-employment",
    "tradingName": "Company X",
    "accountingPeriods": [
        {
            "start": "2018-04-06",
            "end": "2019-04-05"
        }
    ],
    "accountingType": "CASH",
    "commencementDate": "2018-04-06",
    "cessationDate": "2019-04-05",
    "businessAddressLineOne": "100 Street",
    "businessAddressLineTwo": "Workingham",
    "businessAddressLineThree": "Surrey",
    "businessAddressLineFour": "London",
    "businessAddressPostcode": "A12 3BC",
    "businessAddressCountryCode": "GB",
    "links": [
        {
            "href": "/individuals/business/details/WW202851A/XAIS12345678901",
            "method": "GET",
            "rel": "self"
        }
    ]
}
```
But when I'm trying to list their update periods by business ID it returns error:

```
GET: https://test-api.service.hmrc.gov.uk/self-assessment/ni/WW202851A/self-employments/XAIS12345678901/periods
RESPONSE:
{
    "code": "MATCHING_RESOURCE_NOT_FOUND",
    "message": "A resource with the name in the request can not be found in the API"
}
```
Also I get the same error when trying to add self-employment business:

```
POST: https://test-api.service.hmrc.gov.uk/self-assessment/ni/WW202851A/self-employments
POST BODY:
{
  "accountingPeriod": {
    "start": "2021-04-06",
    "end": "2022-04-05"
  },
  "accountingType": "CASH",
  "commencementDate": "2016-01-01",
  "tradingName": "Acme Ltd.",
  "businessAddressLineOne": "1 Acme Rd.",
  "businessAddressLineTwo": "London",
  "businessAddressLineThree": "Greater London",
  "businessAddressLineFour": "United Kingdom",
  "businessPostcode": "A9 9AA"
}
RESPONSE:
{
    "code": "MATCHING_RESOURCE_NOT_FOUND",
    "message": "A resource with the name in the request can not be found in the API"
}
```
Could you advise on how to use test environment to get update periods for test individuals.

**Comment by hmrc-api-team** [comment]
Hi @anlar 

I can't reproduce the 404 error when trying to add a self employment (in the self-assessment-api), but using the body you provided worked for me.

![image](https://user-images.githubusercontent.com/66629710/127336993-c1492a41-e366-4576-ab96-7ecb6a24df9e.png)

One important thing to note is, unfortunately the self-assessment-api is "stateful" and requires the `selfEmploymentId` returned in the header value "Location" to be used in the periodics and annuals requests. Using the `businessId` from business-details-api will not work.

Using the dates in your create SE requests, I could also successfully create a periodic submission
![image](https://user-images.githubusercontent.com/66629710/127337400-2fd27314-25fe-4d98-8631-4a3f824079fd.png)

Again, the test data for periodics and annuals within self-assessment-api is "stateful" and you will not be able to retrieve a period without first submitting one. All the other APIs are "stateless" and return success responses as a default in the Sandbox. The stateful test data is something we are looking to phase out soon. 

Hopefully this helps, let me know if you still have issues.

**Comment by anlar** [comment]
Thank you for your explanation. I have found an issue, was using wrong `Accept: application/vnd.hmrc.1.0+json` header. Changed it to `2.0` and everything works fine now.
