### ISSUE TITLE
No configuration for services.json provided

### ISSUE THREAD

**Issue by safianali** [hmrc/self-assessment-api#838]
I'm trying to run the API locally, and have installed servicemanager using the instructions [here](https://github.com/hmrc/service-manager/wiki/Install). When I try to run "sm --start MTDFB_SA", it fails as there is no configuration in service-manager-config/services.json. What should be placed here in order for sm to run successfully? The documentation here and of service-manager doesn't make it clear.

**Comment by hmrc-api-team** [comment]
Although service-manager and the MTD APIs are open source, public repositories they are intended for internal HMRC use. 
So unfortunately you will not be able to use service-manager to run MTD APIs locally.
