### ISSUE TITLE
getting 404 not found on a few end points 

### ISSUE THREAD

**Issue by Stupax3** [hmrc/self-assessment-api#846]
Hi,
I am not 100% sure what I am doing wrong so.

This works
https://test-api.service.hmrc.gov.uk/individuals/business/details/XT909122B/list
and returns this
`"listOfBusinesses": [
        {
            "typeOfBusiness": "self-employment",
            "businessId": "XBIS12345678901",
            "tradingName": "Company X",
            "links": [
                {
                    "href": "/individuals/business/details/XT909122B/XBIS12345678901",
                    "method": "GET",
                    "rel": "retrieve-business-details"
                }
            ]
        }
    ],
    "links": [
        {
            "href": "/individuals/business/details/XT909122B/list",
            "method": "GET",
            "rel": "self"
        }
    ]
}`

this works 
https://test-api.service.hmrc.gov.uk/individuals/self-assessment/income-summary/XT909122B/self-employment?taxYear=2019-20&selfEmploymentId=XBIS12345678901

and returns this 

`{
    "total": {
        "income": 242.86,
        "expenses": 74.3,
        "additions": 91.66,
        "deductions": 30
    },
    "accountingAdjustments": 130.34,
    "profit": {
        "net": 86.24,
        "taxable": 48.7
    }
}`

My issues are -

https://test-api.service.hmrc.gov.uk/self-assessment/ni/XT909122B/self-employments/XBIS12345678901/periods
is returning a 404 not found?

**Comment by Stupax3** [comment]
is no one about that can help?

**Comment by hmrc-api-team** [comment]
Hi @Stupax3

Apologies for the late response. This repository is not actively monitored for new Issues - [per the Documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#support), new Issues should be raised in the [income-tax-mtd-changelog GitHub page](https://github.com/hmrc/income-tax-mtd-changelog/issues).

To answer your questions though, [self-assessment-biss-api](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-biss-api/1.0) and [business-details-api](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/business-details-api/1.0) both use stateless data in Sandbox, meaning that they don't require you to set up your own data to make successful requests (instead you should use Gov-Test Scenario headers to simulate different scenarios). The [List all self-employment update periods](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#List%20all%20self-employment%20update%20periods) endpoint however is stateful. Quoting the documentation:

> You will need to add a self-employment business in the sandbox environment before making a request. This endpoint will return the previously submitted data.

This means you'll need to [Add a self-employment business](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Add%20a%20self-employment%20business%20[test%20support]) and, using the selfEmploymentId retrieved from the Location header from your first request, [Create a self-employment periodic update](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Create%20a%20self-employment%20periodic%20update) before you can retrieve your update periods.

Hopefully this clears up any issues you have. Please raise an Issue in the [income-tax-mtd-changelog GitHub page](https://github.com/hmrc/income-tax-mtd-changelog/issues) if you have any further problems.

**Comment by Stupax3** [comment]
Thanks for the reply
