### ISSUE TITLE
Swagger Document

### ISSUE THREAD

**Issue by andyws** [hmrc/self-assessment-api#94]
Can you provide the swagger document or equivalent for the self assessment api?

The api and its data types are sufficiently extensive to make this a necessity.

**Comment by alexec** [comment]
Hi Andy,

We don't currently have a Swagger specification document for the API. Discussions are underway, and we'll attempt to keep you updated when they are complete.

Alex

**Comment by alexec** [comment]
Hi @andyws , we won't now be providing Swagger, instead we'll be providing RAML.

**Comment by andyws** [comment]
Hi Alex, do you have an eta for the RAML?

**Comment by alexec** [comment]
Hi Andy, we are dependant on another team to build in the feature. It is likely to be in the range of months.
